<?php 

use Zend\Session\Container;
$sessionEmploye = new Container('employe');

$typeProfil = $sessionEmploye->offsetGet("type_profil");
$visite = $consultation->getVisite();
$prestataire = $visite->getPrestataire();
$adherent = $visite->getCodeAdherent();
$ayantDroit = $visite->getCodeAyantDroit();

$prestataire->afficheChaine();
$adherent->afficheChaine();


$malade = $adherent->getAssurePrincipal();


$nomAyantDroit = "";
if($ayantDroit)
{
    $ayantDroit->afficheChaine();
    $nomAyantDroit = $ayantDroit->getNom();
}


// $paramsTauxCouverture = array("typePrestation" => $consultation->getTypeConsultation(), "police" => $adherent->getPolice(), "groupe" => $adherent->getGroupe());
// $objetTauxPrestation = $this->getEntityManager()->getRepository('Entity\TauxPrestation')->findOneBy($paramsTauxCouverture);
// if($objetTauxPrestation)
// {
//     $tauxCouverture = $objetTauxPrestation->getTaux();
// }
// else
// {
//     $tauxCouverture = 0;
// }


if($consultation->getEtatConsultation() == "valide" || $consultation->getEtatConsultation() == "encaisse")
{
    $tauxCouverture = $consultation->getTaux();
    $montantPropose = $consultation->getMontantModif();
}
else
{
    $paramsTauxCouverture = array("typePrestation" => $consultation->getTypeConsultation(), "police" => $adherent->getPolice(), "groupe" => $adherent->getGroupe());
    $objetTauxPrestation = $this->getEntityManager()->getRepository('Entity\TauxPrestation')->findOneBy($paramsTauxCouverture);
    if($objetTauxPrestation)
    {
        $tauxCouverture = $objetTauxPrestation->getTaux();
        $plafond = $objetTauxPrestation->getPlafond();
        
        if(empty($tauxCouverture))
        {
            $tauxCouverture = 0;
        }
        
        if(empty($plafond))
        {
            $montantPropose = $consultation->getMontant();
        }
        else
        {
            $montantPropose = min(array($plafond, $consultation->getMontant()));
        }
    }
    else
    {
        $tauxCouverture = 0;
        $plafond = 0;
        $montantPropose = $element->getMontant();
    }
}


$montantValide = $consultation->getMontantModif();
$montantAssurance = $montantValide*($tauxCouverture/100);
$montantAssure = $montantValide - $montantAssurance;



$tabLigne = array();

$tabLigne[] = array("label" => $this->getTranslator("Prestation n°"), "valeur" => $visite->getCodeCourt());
$tabLigne[] = array("label" => $this->getTranslator("Assure"), "valeur" => $adherent->getAssurePrincipal());

if($ayantDroit)
{
    $malade = $nomAyantDroit;
}

$tabLigne[] = array("label" => $this->getTranslator("Malade"), "valeur" => $malade);

$tabLigne[] = array("label" => $this->getTranslator("Souscripteur"), "valeur" => $adherent->getSouscripteur());
$tabLigne[] = array("label" => $this->getTranslator("Taux de couverture"), "valeur" => $tauxCouverture."%");
$tabLigne[] = array("label" => $this->getTranslator("Type de consultation"), "valeur" => $consultation->getTypeConsultation()->getNom());


// $tabLigne[] = array("label" => $this->getTranslator("Montant valide"), "valeur" => number_format($montantValide, 0, ",", " ")." ".$this->getTranslator("FCFA"));
// $tabLigne[] = array("label" => $this->getTranslator("Montant paye par Zenithe"), "valeur" => number_format($montantAssurance, 0, ",", " ")." ".$this->getTranslator("FCFA"));
// $tabLigne[] = array("label" => $this->getTranslator("Part assure"), "valeur" => number_format($montantAssure, 0, ",", " ")." ".$this->getTranslator("FCFA"));





$varRetour .= '<div id="cntneurDocExportPdf" class="cntneurDocExportPdf" style="background: #333 !important;">';

$varRetour .=   $this->construireEnteteDocPDF();

$varRetour .= ' <div class="ctneurTitreExport" id="ctneurTitreExport"><h4 style="margin-bottom: 20px; margin-top: 20px; text-align: center; font-size: 25px; font-weight: bold;">'.$this->getTranslator("BON DE PRISE EN CHARGE CONSULTATION").'</h4></div>';



$dateEncaisse = "";
if($consultationAudit)
{
    $dateEncaisse = $consultationAudit->getDate()->format("d/m/Y H:i");
}





$varRetour .= '<div style="margin-bottom: 20px;"><table class="table dataTable table-striped"><tbody>';

$varRetour .= '  <tr style="border: solid 1px #ddd !important;">';

$varRetour .= '  <td style="width: 70%; font-weight: bold; border-top: solid 1px #ddd !important;">'.$prestataire->getNom().'</td>';
$varRetour .= '  <td style="width: 30%; border-top: solid 1px #ddd !important;">'.$this->getTranslator("Date heure")." ".$dateEncaisse.'</td>';

$varRetour .= '  </tr>';



$varRetour .= '  </tbody></table></div>';


















$varRetour .= '<table class="table dataTable table-striped"><tbody>';



foreach ($tabLigne as $uneLigne)
{
    $varRetour .= '  <tr>';
    
    $varRetour .= '  <td style="width: 30%; font-weight: bold;">'.$uneLigne['label'].'</td>';
    $varRetour .= '  <td style="width: 70%">'.$uneLigne['valeur'].'</td>';
    
    $varRetour .= '  </tr>';
}



$varRetour .= '  </tbody></table>';






// $varRetour .= '<div style="margin-top: 40px;"><table class="table dataTable table-striped"><tbody>';

// $varRetour .= '  <tr style="border: 0">';
// $varRetour .= '  <td style="width: 80%; font-weight: bold; text-align: right; border: 0;">'.$this->getTranslator("Montant valide").'</td>';
// $varRetour .= '  <td style="width: 20%; text-align: right; border: 0;">'.number_format($montantValide, 0, ",", " ")." ".$this->getTranslator("FCFA").'</td>';
// $varRetour .= '  </tr>';


// $varRetour .= '  <tr style="border: 0">';
// $varRetour .= '  <td style="width: 80%; font-weight: bold; text-align: right; border: 0;">'.$this->getTranslator("Part ZENITHE").'</td>';
// $varRetour .= '  <td style="width: 20%; text-align: right; border: 0;">'.number_format($montantAssurance, 0, ",", " ")." ".$this->getTranslator("FCFA").'</td>';
// $varRetour .= '  </tr>';


// $varRetour .= '  <tr style="border: 0">';
// $varRetour .= '  <td style="width: 80%; font-weight: bold; text-align: right; border: 0;">'.$this->getTranslator("Part assure").'</td>';
// $varRetour .= '  <td style="width: 20%; text-align: right; border: 0;">'.number_format($montantAssure, 0, ",", " ")." ".$this->getTranslator("FCFA").'</td>';
// $varRetour .= '  </tr>';




// $varRetour .= '  </tbody></table></div>';



$tabLigne = array();

$tabLigne[] = array("label" => $this->getTranslator("Montant valide"), "valeur" => number_format($montantValide, 0, ",", " ")." ".$this->getTranslator("FCFA"));
$tabLigne[] = array("label" => $this->getTranslator("Part ZENITHE"), "valeur" => number_format($montantAssurance, 0, ",", " ")." ".$this->getTranslator("FCFA"));
$tabLigne[] = array("label" => $this->getTranslator("Part assure"), "valeur" => number_format($montantAssure, 0, ",", " ")." ".$this->getTranslator("FCFA"));

$varRetour .= '<div style="margin-top: 40px;"><table class="table dataTable table-striped"><tbody>';
foreach ($tabLigne as $uneLigne)
{
    $varRetour .= '  <tr style="border: 0">';
    
    $varRetour .= '  <td style="width: 80%; font-weight: bold; text-align: right; border: 0;">'.$uneLigne['label'].'</td>';
    $varRetour .= '  <td style="width: 20%; text-align: right; border: 0;">'.$uneLigne['valeur'].'</td>';
    
    $varRetour .= '  </tr>';
}
$varRetour .= '  </tbody></table></div>';









$varRetour .= '<table class="table" style="margin-top: 50px; border: 0;"><tbody>';
$varRetour .= '  <tr style="border: 0;">';
$varRetour .= '     <td style="width: 50%; border: 0;">'.$this->getTranslator("L'assure").'</td>';
$varRetour .= '     <td style="width: 50%; border: 0; text-align: right">'.$this->getTranslator("Le prestataire").'</td>';
$varRetour .= '  </tr>';
$varRetour .= '  </tbody></table>';


$varRetour .= '</div>';

?>