<?php

namespace DoctrineORMModule\Proxy\__CG__\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Utilisateur extends \Entity\Utilisateur implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'genre', 'type', 'nom', 'prenom', 'dateNaissance', 'lieuNaissance', 'telephone', 'telephoneIso2', 'telephoneDialCode', 'email', 'login', 'motPasse', 'statut', 'supprime', 'newsletter', 'dateCreation', 'oauthProvider', 'oauthUid', 'localisation', 'activite', 'situationMatrimoniale', 'langueDefaut', 'inputFilter', 'em'];
        }

        return ['__isInitialized__', 'id', 'genre', 'type', 'nom', 'prenom', 'dateNaissance', 'lieuNaissance', 'telephone', 'telephoneIso2', 'telephoneDialCode', 'email', 'login', 'motPasse', 'statut', 'supprime', 'newsletter', 'dateCreation', 'oauthProvider', 'oauthUid', 'localisation', 'activite', 'situationMatrimoniale', 'langueDefaut', 'inputFilter', 'em'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Utilisateur $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * {@inheritDoc}
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);

        parent::__clone();
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setGenre($genre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGenre', [$genre]);

        return parent::setGenre($genre);
    }

    /**
     * {@inheritDoc}
     */
    public function getGenre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGenre', []);

        return parent::getGenre();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom($prenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', [$prenom]);

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', []);

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateNaissance($dateNaissance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateNaissance', [$dateNaissance]);

        return parent::setDateNaissance($dateNaissance);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateNaissance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateNaissance', []);

        return parent::getDateNaissance();
    }

    /**
     * {@inheritDoc}
     */
    public function setLieuNaissance($lieuNaissance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLieuNaissance', [$lieuNaissance]);

        return parent::setLieuNaissance($lieuNaissance);
    }

    /**
     * {@inheritDoc}
     */
    public function getLieuNaissance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLieuNaissance', []);

        return parent::getLieuNaissance();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephone($telephone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephone', [$telephone]);

        return parent::setTelephone($telephone);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephone', []);

        return parent::getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephoneIso2($telephoneIso2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephoneIso2', [$telephoneIso2]);

        return parent::setTelephoneIso2($telephoneIso2);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephoneIso2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephoneIso2', []);

        return parent::getTelephoneIso2();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephoneDialCode($telephoneDialCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephoneDialCode', [$telephoneDialCode]);

        return parent::setTelephoneDialCode($telephoneDialCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephoneDialCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephoneDialCode', []);

        return parent::getTelephoneDialCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setLogin($login)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLogin', [$login]);

        return parent::setLogin($login);
    }

    /**
     * {@inheritDoc}
     */
    public function getLogin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogin', []);

        return parent::getLogin();
    }

    /**
     * {@inheritDoc}
     */
    public function setMotPasse($motPasse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMotPasse', [$motPasse]);

        return parent::setMotPasse($motPasse);
    }

    /**
     * {@inheritDoc}
     */
    public function getMotPasse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMotPasse', []);

        return parent::getMotPasse();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatut($statut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatut', [$statut]);

        return parent::setStatut($statut);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatut', []);

        return parent::getStatut();
    }

    /**
     * {@inheritDoc}
     */
    public function setSupprime($supprime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSupprime', [$supprime]);

        return parent::setSupprime($supprime);
    }

    /**
     * {@inheritDoc}
     */
    public function getSupprime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSupprime', []);

        return parent::getSupprime();
    }

    /**
     * {@inheritDoc}
     */
    public function setNewsletter($newsletter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNewsletter', [$newsletter]);

        return parent::setNewsletter($newsletter);
    }

    /**
     * {@inheritDoc}
     */
    public function getNewsletter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNewsletter', []);

        return parent::getNewsletter();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreation($dateCreation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreation', [$dateCreation]);

        return parent::setDateCreation($dateCreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreation', []);

        return parent::getDateCreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setOauthProvider($oauthProvider)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOauthProvider', [$oauthProvider]);

        return parent::setOauthProvider($oauthProvider);
    }

    /**
     * {@inheritDoc}
     */
    public function getOauthProvider()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOauthProvider', []);

        return parent::getOauthProvider();
    }

    /**
     * {@inheritDoc}
     */
    public function setOauthUid($oauthUid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOauthUid', [$oauthUid]);

        return parent::setOauthUid($oauthUid);
    }

    /**
     * {@inheritDoc}
     */
    public function getOauthUid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOauthUid', []);

        return parent::getOauthUid();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocalisation($localisation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocalisation', [$localisation]);

        return parent::setLocalisation($localisation);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocalisation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocalisation', []);

        return parent::getLocalisation();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivite($activite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivite', [$activite]);

        return parent::setActivite($activite);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivite', []);

        return parent::getActivite();
    }

    /**
     * {@inheritDoc}
     */
    public function setSituationMatrimoniale($situationMatrimoniale)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSituationMatrimoniale', [$situationMatrimoniale]);

        return parent::setSituationMatrimoniale($situationMatrimoniale);
    }

    /**
     * {@inheritDoc}
     */
    public function getSituationMatrimoniale()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSituationMatrimoniale', []);

        return parent::getSituationMatrimoniale();
    }

    /**
     * {@inheritDoc}
     */
    public function setLangueDefaut(\Entity\Langue $langueDefaut = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLangueDefaut', [$langueDefaut]);

        return parent::setLangueDefaut($langueDefaut);
    }

    /**
     * {@inheritDoc}
     */
    public function getLangueDefaut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLangueDefaut', []);

        return parent::getLangueDefaut();
    }

    /**
     * {@inheritDoc}
     */
    public function exchangeArray($data, $entityManager = NULL, $overwrite = false, $excludedValues = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'exchangeArray', [$data, $entityManager, $overwrite, $excludedValues]);

        return parent::exchangeArray($data, $entityManager, $overwrite, $excludedValues);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray($withIndex = true, $excludedColumns = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', [$withIndex, $excludedColumns]);

        return parent::toArray($withIndex, $excludedColumns);
    }

    /**
     * {@inheritDoc}
     */
    public function getArrayCopy($withIndex = true, $excludedColumns = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArrayCopy', [$withIndex, $excludedColumns]);

        return parent::getArrayCopy($withIndex, $excludedColumns);
    }

    /**
     * {@inheritDoc}
     */
    public function setInputFilter(\Zend\InputFilter\InputFilterInterface $inputfilter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInputFilter', [$inputfilter]);

        return parent::setInputFilter($inputfilter);
    }

    /**
     * {@inheritDoc}
     */
    public function getInputFilter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInputFilter', []);

        return parent::getInputFilter();
    }

    /**
     * {@inheritDoc}
     */
    public function getEntityManager()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntityManager', []);

        return parent::getEntityManager();
    }

    /**
     * {@inheritDoc}
     */
    public function setEntityManager($em)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEntityManager', [$em]);

        return parent::setEntityManager($em);
    }

    /**
     * {@inheritDoc}
     */
    public function nettoyageChaine($champInterdis = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'nettoyageChaine', [$champInterdis]);

        return parent::nettoyageChaine($champInterdis);
    }

    /**
     * {@inheritDoc}
     */
    public function afficheChaine($champInterdis = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'afficheChaine', [$champInterdis]);

        return parent::afficheChaine($champInterdis);
    }

}
