<?php

namespace DoctrineORMModule\Proxy\__CG__\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Adherent extends \Entity\Adherent implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'codeAdherent', 'assurePrincipal', 'naissance', 'sexe', 'matricule', 'telephone', 'taux', 'souscripteur', 'police', 'effetPolice', 'echeancePolice', 'groupe', 'enrole', 'dateEnrole', 'imprime', 'statut', 'inputFilter', 'em'];
        }

        return ['__isInitialized__', 'codeAdherent', 'assurePrincipal', 'naissance', 'sexe', 'matricule', 'telephone', 'taux', 'souscripteur', 'police', 'effetPolice', 'echeancePolice', 'groupe', 'enrole', 'dateEnrole', 'imprime', 'statut', 'inputFilter', 'em'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Adherent $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * {@inheritDoc}
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);

        parent::__clone();
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCodeAdherent()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getCodeAdherent();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeAdherent', []);

        return parent::getCodeAdherent();
    }

    /**
     * {@inheritDoc}
     */
    public function setAssurePrincipal($assurePrincipal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAssurePrincipal', [$assurePrincipal]);

        return parent::setAssurePrincipal($assurePrincipal);
    }

    /**
     * {@inheritDoc}
     */
    public function getAssurePrincipal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAssurePrincipal', []);

        return parent::getAssurePrincipal();
    }

    /**
     * {@inheritDoc}
     */
    public function setNaissance($naissance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNaissance', [$naissance]);

        return parent::setNaissance($naissance);
    }

    /**
     * {@inheritDoc}
     */
    public function getNaissance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNaissance', []);

        return parent::getNaissance();
    }

    /**
     * {@inheritDoc}
     */
    public function setSexe($sexe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSexe', [$sexe]);

        return parent::setSexe($sexe);
    }

    /**
     * {@inheritDoc}
     */
    public function getSexe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSexe', []);

        return parent::getSexe();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephone($telephone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephone', [$telephone]);

        return parent::setTelephone($telephone);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephone', []);

        return parent::getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    public function setMatricule($matricule)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMatricule', [$matricule]);

        return parent::setMatricule($matricule);
    }

    /**
     * {@inheritDoc}
     */
    public function getMatricule()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatricule', []);

        return parent::getMatricule();
    }

    /**
     * {@inheritDoc}
     */
    public function setTaux($taux)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTaux', [$taux]);

        return parent::setTaux($taux);
    }

    /**
     * {@inheritDoc}
     */
    public function getTaux()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaux', []);

        return parent::getTaux();
    }

    /**
     * {@inheritDoc}
     */
    public function setSouscripteur($souscripteur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSouscripteur', [$souscripteur]);

        return parent::setSouscripteur($souscripteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getSouscripteur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSouscripteur', []);

        return parent::getSouscripteur();
    }

    /**
     * {@inheritDoc}
     */
    public function setPolice($police)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPolice', [$police]);

        return parent::setPolice($police);
    }

    /**
     * {@inheritDoc}
     */
    public function getPolice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPolice', []);

        return parent::getPolice();
    }

    /**
     * {@inheritDoc}
     */
    public function setEffetPolice($effetPolice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEffetPolice', [$effetPolice]);

        return parent::setEffetPolice($effetPolice);
    }

    /**
     * {@inheritDoc}
     */
    public function getEffetPolice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEffetPolice', []);

        return parent::getEffetPolice();
    }

    /**
     * {@inheritDoc}
     */
    public function setEcheancePolice($echeancePolice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEcheancePolice', [$echeancePolice]);

        return parent::setEcheancePolice($echeancePolice);
    }

    /**
     * {@inheritDoc}
     */
    public function getEcheancePolice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEcheancePolice', []);

        return parent::getEcheancePolice();
    }

    /**
     * {@inheritDoc}
     */
    public function setGroupe($groupe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGroupe', [$groupe]);

        return parent::setGroupe($groupe);
    }

    /**
     * {@inheritDoc}
     */
    public function getGroupe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGroupe', []);

        return parent::getGroupe();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnrole($enrole)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnrole', [$enrole]);

        return parent::setEnrole($enrole);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnrole()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnrole', []);

        return parent::getEnrole();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateEnrole($dateEnrole = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateEnrole', [$dateEnrole]);

        return parent::setDateEnrole($dateEnrole);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateEnrole()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateEnrole', []);

        return parent::getDateEnrole();
    }

    /**
     * {@inheritDoc}
     */
    public function setImprime($imprime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImprime', [$imprime]);

        return parent::setImprime($imprime);
    }

    /**
     * {@inheritDoc}
     */
    public function getImprime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImprime', []);

        return parent::getImprime();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatut($statut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatut', [$statut]);

        return parent::setStatut($statut);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatut', []);

        return parent::getStatut();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodeAdherent($codeAdherent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodeAdherent', [$codeAdherent]);

        return parent::setCodeAdherent($codeAdherent);
    }

    /**
     * {@inheritDoc}
     */
    public function exchangeArray($data, $entityManager = NULL, $overwrite = false, $excludedValues = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'exchangeArray', [$data, $entityManager, $overwrite, $excludedValues]);

        return parent::exchangeArray($data, $entityManager, $overwrite, $excludedValues);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray($withIndex = true, $excludedColumns = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', [$withIndex, $excludedColumns]);

        return parent::toArray($withIndex, $excludedColumns);
    }

    /**
     * {@inheritDoc}
     */
    public function getArrayCopy($withIndex = true, $excludedColumns = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArrayCopy', [$withIndex, $excludedColumns]);

        return parent::getArrayCopy($withIndex, $excludedColumns);
    }

    /**
     * {@inheritDoc}
     */
    public function setInputFilter(\Zend\InputFilter\InputFilterInterface $inputfilter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInputFilter', [$inputfilter]);

        return parent::setInputFilter($inputfilter);
    }

    /**
     * {@inheritDoc}
     */
    public function getInputFilter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInputFilter', []);

        return parent::getInputFilter();
    }

    /**
     * {@inheritDoc}
     */
    public function getEntityManager()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntityManager', []);

        return parent::getEntityManager();
    }

    /**
     * {@inheritDoc}
     */
    public function setEntityManager($em)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEntityManager', [$em]);

        return parent::setEntityManager($em);
    }

    /**
     * {@inheritDoc}
     */
    public function nettoyageChaine($champInterdis = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'nettoyageChaine', [$champInterdis]);

        return parent::nettoyageChaine($champInterdis);
    }

    /**
     * {@inheritDoc}
     */
    public function afficheChaine($champInterdis = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'afficheChaine', [$champInterdis]);

        return parent::afficheChaine($champInterdis);
    }

}
