<?php

namespace DoctrineORMModule\Proxy\__CG__\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AyantDroit extends \Entity\AyantDroit implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'codeAyantDroit', 'nom', 'sexe', 'naissance', 'lienpare', 'telephone', 'police', 'enrole', 'dateEnrole', 'statut', 'codeAdherent', 'inputFilter', 'em'];
        }

        return ['__isInitialized__', 'codeAyantDroit', 'nom', 'sexe', 'naissance', 'lienpare', 'telephone', 'police', 'enrole', 'dateEnrole', 'statut', 'codeAdherent', 'inputFilter', 'em'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (AyantDroit $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * {@inheritDoc}
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);

        parent::__clone();
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCodeAyantDroit()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getCodeAyantDroit();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeAyantDroit', []);

        return parent::getCodeAyantDroit();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodeAyantDroit($codeAyantDroit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodeAyantDroit', [$codeAyantDroit]);

        return parent::setCodeAyantDroit($codeAyantDroit);
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setSexe($sexe = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSexe', [$sexe]);

        return parent::setSexe($sexe);
    }

    /**
     * {@inheritDoc}
     */
    public function getSexe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSexe', []);

        return parent::getSexe();
    }

    /**
     * {@inheritDoc}
     */
    public function setNaissance($naissance = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNaissance', [$naissance]);

        return parent::setNaissance($naissance);
    }

    /**
     * {@inheritDoc}
     */
    public function getNaissance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNaissance', []);

        return parent::getNaissance();
    }

    /**
     * {@inheritDoc}
     */
    public function setLienpare($lienpare)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLienpare', [$lienpare]);

        return parent::setLienpare($lienpare);
    }

    /**
     * {@inheritDoc}
     */
    public function getLienpare()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLienpare', []);

        return parent::getLienpare();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephone($telephone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephone', [$telephone]);

        return parent::setTelephone($telephone);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephone', []);

        return parent::getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    public function setPolice($police = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPolice', [$police]);

        return parent::setPolice($police);
    }

    /**
     * {@inheritDoc}
     */
    public function setEnrole($enrole)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnrole', [$enrole]);

        return parent::setEnrole($enrole);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnrole()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnrole', []);

        return parent::getEnrole();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateEnrole($dateEnrole = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateEnrole', [$dateEnrole]);

        return parent::setDateEnrole($dateEnrole);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateEnrole()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateEnrole', []);

        return parent::getDateEnrole();
    }

    /**
     * {@inheritDoc}
     */
    public function getPolice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPolice', []);

        return parent::getPolice();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatut($statut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatut', [$statut]);

        return parent::setStatut($statut);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatut', []);

        return parent::getStatut();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodeAdherent(\Entity\Adherent $codeAdherent = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodeAdherent', [$codeAdherent]);

        return parent::setCodeAdherent($codeAdherent);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeAdherent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeAdherent', []);

        return parent::getCodeAdherent();
    }

    /**
     * {@inheritDoc}
     */
    public function exchangeArray($data, $entityManager = NULL, $overwrite = false, $excludedValues = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'exchangeArray', [$data, $entityManager, $overwrite, $excludedValues]);

        return parent::exchangeArray($data, $entityManager, $overwrite, $excludedValues);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray($withIndex = true, $excludedColumns = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', [$withIndex, $excludedColumns]);

        return parent::toArray($withIndex, $excludedColumns);
    }

    /**
     * {@inheritDoc}
     */
    public function getArrayCopy($withIndex = true, $excludedColumns = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArrayCopy', [$withIndex, $excludedColumns]);

        return parent::getArrayCopy($withIndex, $excludedColumns);
    }

    /**
     * {@inheritDoc}
     */
    public function setInputFilter(\Zend\InputFilter\InputFilterInterface $inputfilter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInputFilter', [$inputfilter]);

        return parent::setInputFilter($inputfilter);
    }

    /**
     * {@inheritDoc}
     */
    public function getInputFilter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInputFilter', []);

        return parent::getInputFilter();
    }

    /**
     * {@inheritDoc}
     */
    public function getEntityManager()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntityManager', []);

        return parent::getEntityManager();
    }

    /**
     * {@inheritDoc}
     */
    public function setEntityManager($em)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEntityManager', [$em]);

        return parent::setEntityManager($em);
    }

    /**
     * {@inheritDoc}
     */
    public function nettoyageChaine($champInterdis = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'nettoyageChaine', [$champInterdis]);

        return parent::nettoyageChaine($champInterdis);
    }

    /**
     * {@inheritDoc}
     */
    public function afficheChaine($champInterdis = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'afficheChaine', [$champInterdis]);

        return parent::afficheChaine($champInterdis);
    }

}
