<?php

namespace DoctrineORMModule\Proxy\__CG__\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Prestation extends \Entity\Prestation implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'naturePrestation', 'date', 'supprime', 'prestataire', 'visite', 'inputFilter', 'em'];
        }

        return ['__isInitialized__', 'id', 'naturePrestation', 'date', 'supprime', 'prestataire', 'visite', 'inputFilter', 'em'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Prestation $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * {@inheritDoc}
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);

        parent::__clone();
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNaturePrestation($naturePrestation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNaturePrestation', [$naturePrestation]);

        return parent::setNaturePrestation($naturePrestation);
    }

    /**
     * {@inheritDoc}
     */
    public function getNaturePrestation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNaturePrestation', []);

        return parent::getNaturePrestation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', [$date]);

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', []);

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setSupprime($supprime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSupprime', [$supprime]);

        return parent::setSupprime($supprime);
    }

    /**
     * {@inheritDoc}
     */
    public function getSupprime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSupprime', []);

        return parent::getSupprime();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrestataire(\Entity\Prestataire $prestataire = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrestataire', [$prestataire]);

        return parent::setPrestataire($prestataire);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrestataire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrestataire', []);

        return parent::getPrestataire();
    }

    /**
     * {@inheritDoc}
     */
    public function setVisite(\Entity\Visite $visite = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVisite', [$visite]);

        return parent::setVisite($visite);
    }

    /**
     * {@inheritDoc}
     */
    public function getVisite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVisite', []);

        return parent::getVisite();
    }

    /**
     * {@inheritDoc}
     */
    public function exchangeArray($data, $entityManager = NULL, $overwrite = false, $excludedValues = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'exchangeArray', [$data, $entityManager, $overwrite, $excludedValues]);

        return parent::exchangeArray($data, $entityManager, $overwrite, $excludedValues);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray($withIndex = true, $excludedColumns = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', [$withIndex, $excludedColumns]);

        return parent::toArray($withIndex, $excludedColumns);
    }

    /**
     * {@inheritDoc}
     */
    public function getArrayCopy($withIndex = true, $excludedColumns = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArrayCopy', [$withIndex, $excludedColumns]);

        return parent::getArrayCopy($withIndex, $excludedColumns);
    }

    /**
     * {@inheritDoc}
     */
    public function setInputFilter(\Zend\InputFilter\InputFilterInterface $inputfilter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInputFilter', [$inputfilter]);

        return parent::setInputFilter($inputfilter);
    }

    /**
     * {@inheritDoc}
     */
    public function getInputFilter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInputFilter', []);

        return parent::getInputFilter();
    }

    /**
     * {@inheritDoc}
     */
    public function getEntityManager()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntityManager', []);

        return parent::getEntityManager();
    }

    /**
     * {@inheritDoc}
     */
    public function setEntityManager($em)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEntityManager', [$em]);

        return parent::setEntityManager($em);
    }

    /**
     * {@inheritDoc}
     */
    public function nettoyageChaine($champInterdis = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'nettoyageChaine', [$champInterdis]);

        return parent::nettoyageChaine($champInterdis);
    }

    /**
     * {@inheritDoc}
     */
    public function afficheChaine($champInterdis = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'afficheChaine', [$champInterdis]);

        return parent::afficheChaine($champInterdis);
    }

}
