<?php

echo $this->headScript()
->prependFile($this->basePath() . '/js/fusioncharts-suite-xt/js/themes/fusioncharts.theme.fusion.js', 'text/javascript')
->prependFile($this->basePath() . '/js/fusioncharts-suite-xt/integrations/jquery/js/jquery-fusioncharts.min.js', 'text/javascript')
->prependFile($this->basePath() . '/js/fusioncharts-suite-xt/js/fusioncharts.js', 'text/javascript');

?>

<div id="chart-container" style="display: none;">FusionCharts XT will load here!</div>


<style type="text/css">

.small-box>.inner {
    padding: 10px;
    min-height: 110px;
}

</style>

<script type="text/javascript">		         
	$(document).ready(function() {
		var chartConfigs = {
				   type: "mscolumn3d",
				   width: "100%",
				   height: "500",
				   dataFormat: "json",
				   dataSource: {
				  "chart": {
				    "caption": "App Publishing Trend",
				    "subcaption": "2012-2016",
				    "xaxisname": "Years",
				    "yaxisname": "Total number of apps in store",
				    "formatnumberscale": "1",
				    "plottooltext": "<b>$dataValue</b> apps were available on <b>$seriesName</b> in $label",
				    "theme": "fusion"
				  },
				  "categories": [
				    {
				      "category": [
				        {
				          "label": "2012"
				        },
				        {
				          "label": "2013"
				        },
				        {
				          "label": "2014"
				        },
				        {
				          "label": "2015"
				        },
				        {
				          "label": "2016"
				        }
				      ]
				    }
				  ],
				  "dataset": [
				    {
				      "seriesname": "iOS App Store",
				      "data": [
				        {
				          "value": "125000"
				        },
				        {
				          "value": "300000"
				        },
				        {
				          "value": "480000"
				        },
				        {
				          "value": "800000"
				        },
				        {
				          "value": "1100000"
				        }
				      ]
				    },
				    {
				      "seriesname": "Google Play Store",
				      "data": [
				        {
				          "value": "70000"
				        },
				        {
				          "value": "150000"
				        },
				        {
				          "value": "350000"
				        },
				        {
				          "value": "600000"
				        },
				        {
				          "value": "1400000"
				        }
				      ]
				    },
				    {
				      "seriesname": "Amazon AppStore",
				      "data": [
				        {
				          "value": "10000"
				        },
				        {
				          "value": "100000"
				        },
				        {
				          "value": "300000"
				        },
				        {
				          "value": "600000"
				        },
				        {
				          "value": "900000"
				        }
				      ]
				    }
				  ]
				}
				};

		$("#chart-container").insertFusionCharts(chartConfigs);
	});

</script>