<?php 

use Zend\Session\Container;
$sessionEmploye = new Container('employe');

// $typeProfil = $sessionEmploye->offsetGet("type_profil");


$typeProfil = $sessionEmploye->offsetGet("type_profil");


$montantValide = 0;
$montantAssurance = 0;
$montantAssure = 0;




$varRetour .= '<div class="" id="cntneurDocExportPdf">';



if($this->naturePrestation == "dentisterie")
{
    $titre = $this->getTranslator("Liste des prestations en dentisterie");
}



if ($sessionEmploye->offsetGet("type_profil") == "prestataire")
{
    $afficherLogo = false;
    $logoEntreprise = $sessionEmploye->offsetGet('logo_prestataire');
    if(!empty($logoEntreprise) && file_exists(__DIR__."/../../../../../public/img/back/prestataire/logo/".$logoEntreprise))
    {
        $afficherLogo = true;
    }
    
    
    $tabParams = array(
        "afficheLogo" =>  $afficherLogo,
        "logoEntreprise" =>  $logoEntreprise,
        "nomEntreprise" =>  $sessionEmploye->offsetGet('nom_prestataire'),
        "adresseEntreprise" =>  $sessionEmploye->offsetGet('adresse_prestataire'),
        "telephoneEntreprise" =>  $sessionEmploye->offsetGet('telephone_prestataire'),
        "registreEntreprise" =>  $sessionEmploye->offsetGet('registre_prestataire'),
    );
}


$varRetour .=   $this->construireEnteteDocPDF("", $tabParams);

$varRetour .= '<div class="ctneurTitreExport" id="ctneurTitreExport">'.$titre.'</div>';


$varRetour .= '<div class="box box-primary box-primary-adminlte">';

// Mettre les elements selectionnes dans le filtre
$varRetour .= '<table class="table table-striped">';


$tabEltsFiltre = array();

// Traitemepnt des valeurs du filtre


if($typeProfil == "admin")
{
    if(!empty($postValues['prestataire']))
    {
        $nomPrestataire = "";
        
        $prestataire = $this->getEntityManager()->find('Entity\Prestataire', $postValues['prestataire']);
        if($prestataire)
        {
            $prestataire->afficheChaine();
            $nomPrestataire = $prestataire->getNom();
        }
        
        
        $tabEltsFiltre[] = array("label" => $this->getTranslator("Prestataire"),
                                 "valeur" => $nomPrestataire);
    }
}
else
{
    $tabEltsFiltre[] = array("label" => $this->getTranslator("Prestataire"),
                             "valeur" => $sessionEmploye->offsetGet("nom_prestataire"));
}

if(!empty($postValues['dateMin']))
{
    $dateMin = new \DateTime(date($postValues['dateMin']));
    
    if($dateMin)
    {
        $tabEltsFiltre[] = array("label" => $this->getTranslator("Date prestation min"),
                                 "valeur" => $dateMin->format("d/m/Y"));
    }
}

if(!empty($postValues['dateMax']))
{
    $dateMax = new \DateTime(date($postValues['dateMax']));
    
    if($dateMax)
    {
        $tabEltsFiltre[] = array("label" => $this->getTranslator("Date prestation max"),
                                 "valeur" => $dateMax->format("d/m/Y"));
    }
}


if(!empty($postValues['dateEncaisseMin']))
{
    $dateEncaisseMin = new \DateTime(date($postValues['dateEncaisseMin']));
    
    if($dateEncaisseMin)
    {
        $tabEltsFiltre[] = array("label" => $this->getTranslator("Date encaisse min"),
            "valeur" => $dateEncaisseMin->format("d/m/Y"));
    }
}

if(!empty($postValues['dateEncaisseMax']))
{
    $dateEncaisseMax = new \DateTime(date($postValues['dateEncaisseMax']));
    
    if($dateEncaisseMax)
    {
        $tabEltsFiltre[] = array("label" => $this->getTranslator("Date encaisse max"),
            "valeur" => $dateEncaisseMax->format("d/m/Y"));
    }
}



if(!empty($postValues['nomAdherent']))
{
    $tabEltsFiltre[] = array("label" => $this->getTranslator("Nom adherent"),
                             "valeur" => $postValues['dateMax']);
}

if(!empty($postValues['nomAyantDroit']))
{
    $tabEltsFiltre[] = array("label" => $this->getTranslator("Nom ayant droit"),
                             "valeur" => $postValues['nomAyantDroit']);
}

if(isset($postValues['idVisite']) && !empty($postValues['idVisite']))
{
    $tabEltsFiltre[] = array("label" => $this->getTranslator("Code visite"),
                             "valeur" => $postValues['idVisite']);
}


$compteur = 0;
foreach ($tabEltsFiltre as $eltFiltre)
{
    if($compteur%2 == 0)
    {
        $varRetour .= '<tr>';
    }
    
    $varRetour .= '<td style="width: 25%;"><b>'.$eltFiltre['label'].'</b></td>';
    $varRetour .= '<td style="width: 25%;">'.$eltFiltre['valeur'].'</td>';
    
    if($compteur%2 == 1)
    {
        $varRetour .= '</tr>';
    }
    
    $compteur++;
}

if($compteur%2 == 1)
{
    $varRetour .= '<td style="width: 25%;"></td>';
    $varRetour .= '<td style="width: 25%;"></td>';
    $varRetour .= '</tr>';
}



$varRetour .= '</table>';





$varRetour .= '</div>';


$titreListeMedicaments = "";
if( $this->naturePrestation == "dentisterie")
{
    $titreListeMedicaments = $this->getTranslator("Liste des prestations en dentisterie");
}


$varRetour .= '<div style="margin-bottom: 30px; margin-top: 30px;">';


$varRetour .= '  <h4>'.$titreListeMedicaments.'</h4>';

$varRetour .= '<table class="table dataTable table-striped">';
$varRetour .= '  <thead>';
$varRetour .= '    <tr>';



if($typeProfil == "admin" && empty($postValues['prestataire']))
{
    $varRetour .= '        <th>'.$this->getTranslator("Prestataire").'</th>';
}


$varRetour .= '        <th>'.$this->getTranslator("Souscripteur").'</th>';
$varRetour .= '        <th>'.$this->getTranslator("Assure principal").'</th>';
$varRetour .= '        <th>'.$this->getTranslator("Malade").'</th>';

if( $this->naturePrestation == "dentisterie")
{
    $varRetour .= '        <th>'.$this->getTranslator("Libelle").'</th>';
	
	$varRetour .= '        <th>'.$this->getTranslator("Dents Concernees").'</th>';

    $varRetour .= '        <th>'.$this->getTranslator("Codification").'</th>';

}


if( $this->naturePrestation == "dentisterie")
{
    $varRetour .= '        <th>'.$this->getTranslator("Categorie").'</th>';
}


$varRetour .= '        <th>'.$this->getTranslator("Taux couverture").'</th>';

$varRetour .= '        <th>'.$this->getTranslator("Date").'</th>';
$varRetour .= '        <th>'.$this->getTranslator("Montant valide").'</th>';
$varRetour .= '        <th>'.$this->getTranslator("Montant paye par Zenithe").'</th>';
$varRetour .= '        <th>'.$this->getTranslator("Part assure").'</th>';


$varRetour .= '    </tr>';
$varRetour .= '  </thead>';





$varRetour .= '  <tbody>';

foreach ($tab as $uneLignePrestation)
{
    $prestation = $uneLignePrestation->getPrestation();
    $prestataire = $uneLignePrestation->getPrestataire();
    
    $visite = $prestation->getVisite();
    $adherent = $visite->getCodeAdherent();
    $ayantDroit = $visite->getCodeAyantDroit();
    
    $adherent->afficheChaine();
    
    $nomAyantDroit = "";
    if($ayantDroit)
    {
        $ayantDroit->afficheChaine();
        $nomAyantDroit = $ayantDroit->getNom();
    }
    
    $nomPrestataire = "";
    if($prestataire)
    {
        $prestataire->afficheChaine();
        $nomPrestataire = $prestataire->getNom();
    }
    
    $dateEncaisse = $uneLignePrestation->getDateEncaisse();
    if($dateEncaisse)
    {
        $dateEncaisse = $dateEncaisse->format("d/m/Y");
    }
    else
    {
        $dateEncaisse = "";
    }
    
    
    $typePrestation = "";
    if( $this->naturePrestation == "dentisterie")
    {
        if($uneLignePrestation->getTypeExamen())
        {
            $typePrestation = $uneLignePrestation->getTypeExamen()->getId();
        }
    }
    
    
    
    //     $paramsTauxCouverture = array("typePrestation" => $typePrestation, "police" => $adherent->getPolice(), "groupe" => $adherent->getGroupe());
    //     $objetTauxPrestation = $this->getEntityManager()->getRepository('Entity\TauxPrestation')->findOneBy($paramsTauxCouverture);
    //     if($objetTauxPrestation)
        //     {
        //         $tauxCouverture = $objetTauxPrestation->getTaux();
        //     }
    //     else
        //     {
        //         $tauxCouverture = 0;
        //     }
    
    
    
    
    if($uneLignePrestation->getEtat() == "valide" || $uneLignePrestation->getEtat() == "encaisse")
    {
        $tauxCouverture = $uneLignePrestation->getTaux();
        $montantPropose = $uneLignePrestation->getValeurModif();
    }
    else
    {
        $paramsTauxCouverture = array("typePrestation" => $typePrestation, "police" => $adherent->getPolice(), "groupe" => $adherent->getGroupe());
        $objetTauxPrestation = $this->getEntityManager()->getRepository('Entity\TauxPrestation')->findOneBy($paramsTauxCouverture);
        if($objetTauxPrestation)
        {
            $tauxCouverture = $objetTauxPrestation->getTaux();
            $plafond = $objetTauxPrestation->getPlafond();
            
            if(empty($tauxCouverture))
            {
                $tauxCouverture = 0;
            }
            
            if(empty($plafond))
            {
                $montantPropose = $uneLignePrestation->getValeur();
            }
            else
            {
                $montantPropose = min(array($plafond, $uneLignePrestation->getValeur()));
            }
        }
        else
        {
            $tauxCouverture = 0;
            $plafond = 0;
        }
    }
    
    
    
    
    $montantValideLigne = $uneLignePrestation->getValeurModif()*$uneLignePrestation->getNbreModif();
    $montantAssuranceLigne = $montantValideLigne*($tauxCouverture/100);
    
    $montantValide += $montantValideLigne;
    $montantAssurance += $montantAssuranceLigne;
    
    
    
    
    
    
    
    $uneLignePrestation->afficheChaine();
    
    $varRetour .= '  <tr>';
    
    if($typeProfil == "admin" && empty($postValues['prestataire']))
    {
        $varRetour .= '        <td>'.$nomPrestataire.'</td>';
    }
    
    $varRetour .= '        <td>'.$adherent->getSouscripteur().'</td>';
    $varRetour .= '        <td>'.$adherent->getAssurePrincipal().'</td>';
    $varRetour .= '        <td>'.$nomAyantDroit.'</td>';
	
	 $descriptionSoins = "";
        if($uneLignePrestation->getDescriptionSoins())
        {
            $descriptionSoins = $uneLignePrestation->getDescriptionSoins()->getNom();
        }
    
    $varRetour .= '        <td>'.$descriptionSoins.'</td>';
	
	$varRetour .= '        <td>'.$uneLignePrestation->getDentsConcernees().'</td>';
	
	$varRetour .= '        <td>'.$uneLignePrestation->getCodification().'</td>';
    
    if( $this->naturePrestation == "dentisterie")
    {
        $nomTypeExamen = "";
        if($uneLignePrestation->getTypeExamen())
        {
            $nomTypeExamen = $uneLignePrestation->getTypeExamen()->getNom();
        }
        
        $varRetour .= '        <td>'.$nomTypeExamen.'</td>';
    }
    
	
	
    
    $varRetour .= '        <td>'.$tauxCouverture.'</td>';
    
    $varRetour .= '        <td>'.$dateEncaisse.'</td>';
    
    $varRetour .= '        <td>'.$montantValideLigne.'</td>';
    $varRetour .= '        <td>'.($montantAssuranceLigne).'</td>';
    $varRetour .= '        <td>'.($montantValideLigne - $montantAssuranceLigne).'</td>';
    
    
    
    $varRetour .= '  </tr>';
}

$varRetour .= '   </tbody>';
$varRetour .= '  </table></div>';


$montantAssure = $montantValide - $montantAssurance;






$tabLigne = array();

$tabLigne[] = array("label" => $this->getTranslator("Montant total valide"), "valeur" => number_format($montantValide, 0, ",", " ")." ".$this->getTranslator("FCFA"));
$tabLigne[] = array("label" => $this->getTranslator("Montant paye par Zenithe"), "valeur" => number_format($montantAssurance, 0, ",", " ")." ".$this->getTranslator("FCFA"));
$tabLigne[] = array("label" => $this->getTranslator("Part assure"), "valeur" => number_format($montantAssure, 0, ",", " ")." ".$this->getTranslator("FCFA"));

$varRetour .= '<table class="table dataTable table-striped"><tbody>';
foreach ($tabLigne as $uneLigne)
{
    $varRetour .= '  <tr>';
    
    $varRetour .= '  <td style="width: 30%; font-weight: bold;">'.$uneLigne['label'].'</td>';
    $varRetour .= '  <td style="width: 70%">'.$uneLigne['valeur'].'</td>';
    
    $varRetour .= '  </tr>';
}
$varRetour .= '  </tbody></table>';



$varRetour .= '</div>';

$varRetour .= '
<style type="text/css">
    
    .ctneurTotaux {
        text-align: right;
        margin-bottom: 50px;
        font-size: 18px;
    }
    
    .titreTotal, .valeurTotal {
        display: inline-block;
    }
    
    .valeurTotal {
        font-weight: bold;
    }
</style>';













$varRetour .= '  </div>';

?>