<?php 
	$appliConfig =  new \Application\Core\AppliConfig();
?>

<div class="container">
	<div class="navbar-header">
		<button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
			<span class="sr-only"><?= $this->translate("Toggle navigation", "application"); ?></span>
            <span class="icon-bar"></span>
		</button>
		<a class="navbar-brand"><b><?= $appliConfig->get("nom_appli"); ?></b></a>
	</div>
	<div class="navbar-collapse collapse" id="navbar">
		<ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              	<a aria-expanded="false" aria-haspopup="true" role="button" data-toggle="dropdown" class="dropdown-toggle" href="#"><?= $this->translate("Language", "application"); ?> : English <span class="caret"></span></a>
              	<ul class="dropdown-menu">
                	<li>
                		<a href="#">Français</a>
                	</li>
				</ul>
			</li>
		</ul>
	</div><!--/.nav-collapse -->
</div>