<?= $this->doctype(); ?>

<?php
	use Zend\Session\Container;
	
	$sessionEmploye = new Container('employe');
	$sessionAgence = new Container('agence');
	
	$appliConfig =  new \Application\Core\AppliConfig();
?>

<html lang="<?= $sessionEmploye->offsetGet("lang"); ?>">
    <head>
		<meta charset="utf-8" />
		
		<!-- Pour empecher l'indexation des pages du backoffice -->
		<meta name="robots" content="noindex,nofollow" />
		
		<?= $this->headTitle($this->nomPage." - ".$sessionAgence->offsetGet("nom"))->setSeparator(' - ')->setAutoEscape(false) ?>
		
		<!-- Tell the browser to be responsive to screen width -->
		<?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        
        <!-- Le styles -->
        <?= $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        				->prependStylesheet($this->basePath('css/backoffice.css'))
        				->prependStylesheet($this->basePath('css/style.css'))
        				->prependStylesheet($this->basePath('css/jquery.alerts.css'))
        				->prependStylesheet ($this->basePath().'/js/jquery-confirm-master-v3-0-1/css/jquery-confirm.css')
        				->prependStylesheet ($this->basePath().'/js/spinner-on-div/spinnerQueue.css')
        				->prependStylesheet($this->basePath('AdminLTE-2.2.1/plugins/iCheck/all.css'))
                        ->prependStylesheet($this->basePath('AdminLTE-2.2.1/dist/css/skins/_all-skins.min.css'))
                        ->prependStylesheet($this->basePath('AdminLTE-2.2.1/dist/css/AdminLTE.min.css'))
                        ->prependStylesheet($this->basePath('css/jquery-ui-timepicker-addon.css'))
                        ->prependStylesheet($this->basePath('AdminLTE-2.2.1/plugins/select2/select2.min.css'))
				        ->prependStylesheet($this->basePath('AdminLTE-2.2.1/plugins/ionicons.min.css'))
				        ->prependStylesheet($this->basePath('AdminLTE-2.2.1/plugins/font-awesome.min.css'))
        				
				        ->prependStylesheet($this->basePath('js/jqueryui/development-bundle/themes/base/jquery.ui.all.css'))
				        ->prependStylesheet($this->basePath('AdminLTE-2.2.1/bootstrap/css/bootstrap.min.css')) ?>
        
        
        
        <!-- Scripts -->
        <?= $this->headScript()
        	->prependFile($this->basePath('js/script.js'))
        	->prependFile($this->basePath().'/js/custumPagination.js', 'text/javascript')
        	->prependFile($this->basePath().'/js/language/common_lang_'.$sessionEmploye->offsetGet("code_langue").'.js')
        	
        	->prependFile($this->basePath().'/js/spinner-on-div/spinnerQueue.js', 'text/javascript')
        	
        	// FormValidation
            ->prependFile($this->basePath().'/js/formValidation/js/bootstrap.min.js', 'text/javascript')
            ->prependFile($this->basePath().'/js/formValidation/js/formValidation.min.js', 'text/javascript')
        	
        	->prependFile($this->basePath().'/js/jquery.jqprint-0.3.js', 'text/javascript')
        	->prependFile($this->basePath().'/AdminLTE-2.2.1/plugins/input-mask/jquery.inputmask.numeric.extensions.js', 'text/javascript')
        	->prependFile($this->basePath().'/AdminLTE-2.2.1/plugins/input-mask/jquery.inputmask.extensions.js', 'text/javascript')
        	->prependFile($this->basePath().'/AdminLTE-2.2.1/plugins/input-mask/jquery.inputmask.js', 'text/javascript')
        	->prependFile($this->basePath().'/js/jquery.alerts.js')
        	->prependFile($this->basePath().'/js/jquery-confirm-master-v3-0-1/js/jquery-confirm.js')
        	->prependFile($this->basePath('AdminLTE-2.2.1/plugins/select2/select2.full.min.js'))
        	->prependFile($this->basePath('AdminLTE-2.2.1/plugins/iCheck/icheck.min.js'))
            
            
            ->prependFile($this->basePath('AdminLTE-2.2.1/dist/js/app.min.js'))
            ->prependFile($this->basePath('AdminLTE-2.2.1/bootstrap/js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-ui-timepicker-addon.js'))
            ->prependFile($this->basePath().'/js/jqueryui/development-bundle/ui/minified/jquery.ui.datepicker.min.js', 'text/javascript')
            ->prependFile($this->basePath().'/js/jqueryui/development-bundle/ui/minified/jquery.ui.widget.min.js', 'text/javascript')
            ->prependFile($this->basePath().'/js/jqueryui/development-bundle/ui/minified/jquery.ui.core.min.js', 'text/javascript')
            ->prependFile($this->basePath('AdminLTE-2.2.1/plugins/jQuery/jQuery-2.1.4.min.js'))
        ; ?>
	</head>
	
    <body class="skin-blue sidebar-mini wysihtml5-supported">
		
    
	    <div class="wrapper">
	
	      <header class="main-header">
			<?= $this->header; ?>
	      </header>
	      <!-- Left side column. contains the logo and sidebar -->
	      <aside class="main-sidebar left-side">
	        <?= $this->sidebar; ?>
	      </aside>
	
	      <!-- Content Wrapper. Contains page content -->
	      <div class="content-wrapper right-side">
	        <!-- Content Header (Page header) -->
	        <section class="content-header">
	          <h1>
	            <?= $this->nomPage; ?>
	          </h1>
	          
	          <?= $this->navigation; ?>
	        </section>
	
	        <!-- Main content -->
	        <section class="content">
	        	<div class="row">
					<div class="col-md-12">
						
						<?php if(isset($this->actionsList) && $this->actionsList) : ?>
							<div class="box-header">
								<?= $this->actionsList; ?>
							</div>
						<?php endif ; ?>
						
						<?php if(isset($this->optionsOnglets) && is_array($this->optionsOnglets) && count($this->optionsOnglets) > 0) : ?>

							<div class="box box-primary">
								<?= $this->onglet; ?>
							</div><!-- /.box -->
							
						<?php endif ; ?>
						
						<div class="box box-primary" id="content_form_ajout" idMsbt="contenuPage">
							<?= $this->simpleForm; ?>
							<?= $this->content; ?>
						</div>
					</div>
				</div>
	        	
	        </section> 
	      </div><!-- /.content-wrapper -->
			
		  
	      <footer class="main-footer">
	        <?= $this->footer; ?>
	      </footer>
	
	    </div><!-- ./wrapper -->
    
        <?= $this->inlineScript() ?>
        
        
        <script type="text/javascript">		         
			$(document).ready(function() {
				
				basePathBackoffice = "<?= $this->basePath()."/".$appliConfig->get('lienBackoffice'); ?>";
				
				$("#form_ajout input, #form_ajout select, #form_ajout textarea").addClass("form-control");
				$("#form_ajout label").addClass("col-md-3 control-label");
				$('#form_ajout .box-footer input[type="submit"], #form_ajout .box-footer input[type="button"]').addClass("pull-right");
				// $("#form_ajout select").select2();
				$("#form_ajout select:not(.noSelect2)").select2();
				
				
		        if($(".form-horizontal select + span.select2").length > 0)
				{
					$(".form-horizontal select + span.select2").attr("style", "width: 100%;");
				}
				$("#form_ajout input.number").inputmask('decimal',
			        	{ 
				        	'alias': 'numeric',
				            'groupSeparator': '  ',
				            'autoGroup': true,
				            'digits': 2,
				            'radixPoint': ",",
				            'digitsOptional': false,
				            'allowMinus': false,
				            'rightAlign': false
			          }
			    );
		
				$( "input[type='text'].date" ).datepicker({
		            changeYear: true,
		            changeMonth: true,
		            numberOfMonths: 1,
		            dateFormat: "yy-mm-dd"
		        });
		
				$("input[type='text'].time").timepicker({
		        	hourGrid: 4,
		        	minuteGrid: 10,
		        	timeFormat: 'HH:mm'
		        });
				
				$( "input[type='text'].datetime" ).datetimepicker({
		            changeYear: true,
		            changeMonth: true,
		            numberOfMonths: 1,
		            dateFormat: "yy-mm-dd",
		        	timeFormat: 'HH:mm'
		        });

				$('.ctneurICheck input').iCheck({
			          checkboxClass: 'icheckbox_square-blue',
			          radioClass: 'iradio_square-blue',
			          increaseArea: '20%' // optional
			    });
			});
		</script>
    </body>
</html>