<?= $this->doctype(); ?>

<?php
	use Zend\Session\Container;
	
	$sessionEmploye = new Container('employe');
	$sessionAgence = new Container('agence');
	
	    $typeProfil = $sessionEmploye->offsetGet("type_profil");
		$typeSousProfil = $sessionEmploye->offsetGet("type_sous_profil");
		$prestataireId = $sessionEmploye->offsetGet("id_prestataire");
	
	$appliConfig =  new \Application\Core\AppliConfig();
?>

<html lang="<?= $sessionEmploye->offsetGet("lang"); ?>">
    <head>
		<meta charset="utf-8" />
		
		<!-- Pour empecher l'indexation des pages du backoffice -->
		<meta name="robots" content="noindex,nofollow" />
		
		<?= $this->headTitle($this->nomPage." - ".$sessionAgence->offsetGet("nom"))->setSeparator(' - ')->setAutoEscape(false) ?>
		
		<!-- Tell the browser to be responsive to screen width -->
		<?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        
        <!-- Le styles -->
        <?= $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        				->prependStylesheet($this->basePath('css/style.css'))
        				->prependStylesheet ($this->basePath().'/css/jquery.alerts.css')
						->prependStylesheet ($this->basePath().'/js/jquery-confirm-master-v3-0-1/css/jquery-confirm.css')
        				->prependStylesheet($this->basePath('AdminLTE-2.2.1/plugins/iCheck/all.css'))
        				
        				// ->prependStylesheet ($this->basePath().'/css/metronic/layout.min.css')
        				// ->prependStylesheet ($this->basePath().'/css/metronic/components.min.css')
        				
                        ->prependStylesheet($this->basePath('AdminLTE-2.2.1/dist/css/skins/_all-skins.min.css'))
                        ->prependStylesheet($this->basePath('AdminLTE-2.2.1/dist/css/AdminLTE.min.css'))
                        ->prependStylesheet($this->basePath('AdminLTE-2.2.1/plugins/select2/select2.min.css'))
				        ->prependStylesheet($this->basePath('AdminLTE-2.2.1/plugins/ionicons.min.css'))
				        ->prependStylesheet($this->basePath('AdminLTE-2.2.1/plugins/font-awesome.min.css'))
        
				        ->prependStylesheet($this->basePath('AdminLTE-2.2.1/bootstrap/css/bootstrap.min.css')) ?>
        
        
        
        <!-- Scripts -->
        <?= $this->headScript()
        	->prependFile($this->basePath('js/script.js'))
        	->prependFile($this->basePath().'/js/custumPagination.js', 'text/javascript')
        	->prependFile($this->basePath().'/js/language/common_lang_'.$sessionEmploye->offsetGet("code_langue").'.js')
        	->prependFile($this->basePath().'/js/jquery.jqprint-0.3.js', 'text/javascript')
        	->prependFile($this->basePath().'/AdminLTE-2.2.1/plugins/input-mask/jquery.inputmask.numeric.extensions.js', 'text/javascript')
        	->prependFile($this->basePath().'/AdminLTE-2.2.1/plugins/input-mask/jquery.inputmask.extensions.js', 'text/javascript')
        	->prependFile($this->basePath().'/AdminLTE-2.2.1/plugins/input-mask/jquery.inputmask.js', 'text/javascript')
        	->prependFile($this->basePath().'/js/jquery.alerts.js')
			->prependFile($this->basePath().'/js/jquery-confirm-master-v3-0-1/js/jquery-confirm.js')
        	->prependFile($this->basePath('AdminLTE-2.2.1/plugins/select2/select2.full.min.js'))
        	->prependFile($this->basePath('AdminLTE-2.2.1/plugins/iCheck/icheck.min.js'))
            
            
            ->prependFile($this->basePath('AdminLTE-2.2.1/dist/js/app.min.js'))
            ->prependFile($this->basePath('AdminLTE-2.2.1/bootstrap/js/bootstrap.min.js'))
            ->prependFile($this->basePath('AdminLTE-2.2.1/plugins/jQuery/jQuery-2.1.4.min.js'))
			
			->prependFile($this->basePath('AdminLTE-2.2.1/plugins/chartjs/Chart.min.js'))
			->prependFile($this->basePath('AdminLTE-2.2.1/plugins/fastclick/fastclick.min.js'))
			->prependFile($this->basePath('AdminLTE-2.2.1/dist/js/demo.js'))
			
        ; ?>
		
		<style>
/* unvisited link */
a:link {
  color: white;
}

/* visited link */
a:visited {
  color: green;
}

/* mouse over link */
a:hover {
  color: gray;
}




</style>
		
	</head>
	
    <body onload="initNotify()" class="skin-blue sidebar-mini wysihtml5-supported">
		
    
	    <div class="wrapper">
	
	      <header class="main-header">
			<?= $this->header; ?>
	      </header>
	      <!-- Left side column. contains the logo and sidebar -->
	      <aside class="main-sidebar left-side">
	        <?= $this->sidebar; ?>
	      </aside>
	
	      <!-- Content Wrapper. Contains page content -->
	      <div class="content-wrapper right-side">
	        <!-- Content Header (Page header) -->
	        <section class="content-header">
	          <h1>
	            <?= $this->nomPage; ?>
	          </h1>
	          
	          <?= $this->navigation; ?>
	        </section>
	
	        <!-- Main content -->
			
	        <section class="content">
	        	<?= $this->content; ?>
				<div class="row">
				
		  <?php 
			if ($sessionEmploye->offsetGet("type_profil")=="prestataire")
			{		
			 echo '<a href="http://'.$_SERVER["SERVER_NAME"].'/biometry/public/admin/consultation/ajouter" class="small-box-footer">';
             echo '<div id="dashconsultation" class="col-lg-3 col-xs-6">';
             echo '<div class="small-box bg-aqua">';
             echo '<div class="inner">';
             echo '<h3 id="nbrConsul"></h3>';
             echo '<p id="libelleConsul" style="color: white;"></p>';
             echo '</div>';
             echo '<div class="icon">';
             echo '<i class="ion ion-ios-pulse-strong"></i>';
             echo '</div>';
             echo  '<a href="http://'.$_SERVER["SERVER_NAME"].'/biometry/public/admin/consultation/ajouter" class="small-box-footer">AJOUTER UNE CONSULTATION<i class="fa fa-arrow-circle-right"></i></a>';
             echo '</div>';
            echo '</div>';
			echo '</a>';
			
			
			
			echo '<a href="http://'.$_SERVER["SERVER_NAME"].'/biometry/public/admin/ordonnance/ajouter" class="small-box-footer">';
             echo '<div id="dashordonnance" class="col-lg-3 col-xs-6">'; 
             echo '<div class="small-box bg-green">';
             echo '<div class="inner">';
             echo '<h3 id="nbrOrdonnance"></h3>';
             echo '<p id="libelleOrdonnance" style="color: white;"></p>';
             echo '</div>';
             echo '<div class="icon">';
             echo '<i class="ion ion-document-text"></i>';
             echo '</div>';
             echo  '<a href="http://'.$_SERVER["SERVER_NAME"].'/biometry/public/admin/ordonnance/ajouter" class="small-box-footer">AJOUTER UNE ORDONNANCE<i class="fa fa-arrow-circle-right"></i></a>';
             echo '</div>';
            echo '</div>';
			echo '</a>';
			
			
			echo '<a href="http://'.$_SERVER["SERVER_NAME"].'/biometry/public/admin/examen/ajouter" class="small-box-footer">';
             echo '<div id="dashexamen" class="col-lg-3 col-xs-6">';
             echo '<div class="small-box bg-yellow">';
             echo '<div class="inner">';
             echo '<h3 id="nbrExamen"></h3>';
             echo '<p id="libelleExamen" style="color: white;"></p>';
             echo '</div>';
             echo '<div class="icon">';
             echo '<i class="ion ion-beaker"></i>';
             echo '</div>';
             echo  '<a href="http://'.$_SERVER["SERVER_NAME"].'/biometry/public/admin/examen/ajouter" class="small-box-footer">AJOUTER UN EXAMEN<i class="fa fa-arrow-circle-right"></i></a>';
             echo '</div>';
            echo '</div>';
			echo '</a>';
		    }
			
			else
			{
			echo '<a href="http://'.$_SERVER["SERVER_NAME"].'/biometry/public/admin/consultation" class="small-box-footer">';
             echo '<div id="dashconsultation" class="col-lg-3 col-xs-6">';
             echo '<div class="small-box bg-aqua">';
             echo '<div class="inner">';
             echo '<h3 id="nbrConsul"></h3>';
             echo '<p id="libelleConsul" style="color: white;"></p>';
             echo '</div>';
             echo '<div class="icon">';
             echo '<i class="ion ion-ios-pulse-strong"></i>';
             echo '</div>';
             echo  '<a href="http://'.$_SERVER["SERVER_NAME"].'/biometry/public/admin/consultation" class="small-box-footer">VOIR PLUS<i class="fa fa-arrow-circle-right"></i></a>';
             echo '</div>';
            echo '</div>';
			echo '</a>';

            
            echo '<a href="http://'.$_SERVER["SERVER_NAME"].'/biometry/public/admin/ordonnance" class="small-box-footer">';
             echo '<div id="dashordonnance" class="col-lg-3 col-xs-6">';
             echo '<div class="small-box bg-green">';
             echo '<div class="inner">';
             echo '<h3 id="nbrOrdonnance"></h3>';
             echo '<p id="libelleOrdonnance" style="color: white;"></p>';
             echo '</div>';
             echo '<div class="icon">';
             echo '<i class="ion ion-document-text"></i>';
             echo '</div>';
             echo  '<a href="http://'.$_SERVER["SERVER_NAME"].'/biometry/public/admin/ordonnance" class="small-box-footer">VOIR PLUS<i class="fa fa-arrow-circle-right"></i></a>';
             echo '</div>';
            echo '</div>';
			echo '</a>';

			echo '<a href="http://'.$_SERVER["SERVER_NAME"].'/biometry/public/admin/examen" class="small-box-footer">';
             echo '<div id="dashexamen" class="col-lg-3 col-xs-6">';
             echo '<div class="small-box bg-yellow">';
             echo '<div class="inner">';
             echo '<h3 id="nbrExamen"></h3>';
             echo '<p id="libelleExamen" style="color: white;"></p>';
             echo '</div>';
             echo '<div class="icon">';
             echo '<i class="ion ion-beaker"></i>';
             echo '</div>';
             echo  '<a href="http://'.$_SERVER["SERVER_NAME"].'/biometry/public/admin/examen" class="small-box-footer">VOIR PLUS<i class="fa fa-arrow-circle-right"></i></a>';
             echo '</div>';
            echo '</div>';
			echo '</a>';
            }				
		 ?>
	
			
			   </div>
			   
			    <div class="row" id="divGraph" style="display: none;">
              
            <div class="col-md-12">
              <!-- BAR CHART -->
              <div class="box box-success">
                <div class="box-header with-border">
				 <div class="row">
				<div class="col-md-6">
                  <h3 id="titreGraph" class="box-title">CONSOMMATION PAR TYPE DE PRESTATIONS</h3>
				   </div>
				   </div>
				    <div class="row">
				   <div class="col-md-6">
				  <div class="form-group">
                      <label>ANNEE</label>
<?php

$year = date("Y");

$options = array( '2018', '2019','2020', '2021', '2022','2023','2024','2025', '2026','2027', '2028', '2029','2030','2031','2032', '2033','2034');

$output = '';
for( $i=0; $i<count($options); $i++ ) {
  $output .= '<option ' 
             . ( $year == $options[$i] ? 'selected="selected"' : '' ) . '>' 
             . $options[$i] 
             . '</option>';
}

echo '<select id="selectAnnee" class="form-control">';
echo $output;
echo '</select>';

?>
                    </div>
					</div>
					 </div>
                  <div class="box-tools pull-right">	    
                    <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                  </div>
                </div>
                <div class="box-body">
                  <div class="chart" id="chartDiv">
                    
					 
                  </div>
                </div><!-- /.box-body -->
              </div><!-- /.box -->
			  </div>
			   <div style="margin: auto; width: 50%;" >
			   <span class="bg-light-blue color-palette"> Consultations</span>
			  <span class="bg-green color-palette">Ordonnances</span>
			    <span class="bg-yellow color-palette">Examens </span>
					 
			     </div>
			 </div>
			   
			   
	        </section> 
			
	      </div><!-- /.content-wrapper -->
			
		  
	      <footer class="main-footer">
	        <?= $this->footer; ?>
	      </footer>
	
	    </div><!-- ./wrapper -->
    
        <?= $this->inlineScript() ?>
        
        
        <script type="text/javascript">		
		
		
			$(document).ready(function() {
			if ('<?php echo $typeProfil; ?>'== "admin")
				$('#divGraph').fadeIn();
				
			if ('<?php echo $typeSousProfil; ?>'== "pharmacie")
			{
				$('#dashconsultation').hide();
				$('#dashexamen').hide();
			}
			
			if ('<?php echo $typeSousProfil; ?>'== "laboratoire")
			{
				$('#dashconsultation').hide();
				$('#dashordonnance').hide();
			}	
				
			
			$('#chartDiv').append(
                           $('<canvas/>')
                         .attr("id", "barChart-"+$( "#selectAnnee").val())
                              );
							  
							$("#barChart-"+$( "#selectAnnee").val()).css("height","230px");
	 		
			 
				var tabConsultation;
				basePathBackoffice = "<?= $this->basePath(); ?>/<?= $appliConfig->get('lienBackoffice'); ?>";
				
				$("select").select2();
				
				$("#titreGraph" ).text("CONSOMMATION PAR TYPE DE PRESTATIONS, ANNEE: "+$( "#selectAnnee" ).val());
				showmsg4();
				
				
				
			});
			
			$('select').change(function () {
         $("#titreGraph" ).text("CONSOMMATION PAR TYPE DE PRESTATIONS, ANNEE: "+$( "#selectAnnee" ).val());
		 
		
    $('#chartDiv').append(
    $('<canvas/>')
    .attr("id", "barChart-"+$( "#selectAnnee").val())
    );
	
	$("#barChart-"+$( "#selectAnnee").val()).css("height","230px");
		

		 
		 
		 // $('canvas').attr('id', "barChart-"+$( "#selectAnnee").val());
		  //$('#chartDiv').not("#barChart-"+$( "#selectAnnee").val()).hide();
		 
		 //$('#chartDiv :not(select)');
		 $('#chartDiv').children().hide();
		 $("#barChart-"+$( "#selectAnnee").val()).show();
		 
		 showmsg4();
           
		   
		   
		   });
			
			var showmsg4 = function() {
							$.ajax({
							  method: 'POST',
							  url: 'http://<?php echo $_SERVER['SERVER_NAME'];?>/biometry/module/Application/view/backoffice/showstatistic.php?typeprofil=<?php echo $typeProfil; ?>&prestataireId=<?php echo $prestataireId; ?>&annee='+$("#selectAnnee" ).val()	  
							})
							.done(function(msg){
								var tab = jQuery.parseJSON(msg);
								tab.forEach(function(message){
								
								if ($("#selectAnnee" ).val()=="2018")
								{
							    var tabA=message.nombrecon;
								 var tabB=message.nombreord;
								  var tabC=message.nombreexa;
								  const tbA=["0","0","0","0","0","0","0","0","0","0"];
								   const tbB=["0","0","0","0","0","0","0","0","0","0"];
								    const tbC=["0","0","0","0","0","0","0","0","0","0"];
								  console.log(tbA.concat(tabA));
								tabConsultation = tbA.concat(tabA).map(Number);
								tabOrdonnance = tbB.concat(tabB).map(Number);
								tabExamen = tbC.concat(tabC).map(Number);
								
								}
								else
								{
								
			                    var tabA=message.nombrecon;
								 var tabB=message.nombreord;
								  var tabC=message.nombreexa;
								 
								tabConsultation = tabA.map(Number);
								tabOrdonnance = tabB.map(Number);
								tabExamen = tabC.map(Number);
								}
								
								///
								 $(function () {
       
       
        var areaChartData = {
          labels: ["Janvier", "Fevrier", "Mars", "Avril", "Mai", "Juin", "Juillet","Août","septembre","Octobre","Novembre","Decembre"],
          datasets: [
            {
              label: "Consultations",
              fillColor: "rgba(60,141,188,0.9)",
              strokeColor: "rgba(60,141,188,0.8)",
              pointColor: "#3b8bba",
              pointStrokeColor: "rgba(60,141,188,1)",
              pointHighlightFill: "#fff",
              pointHighlightStroke: "rgba(60,141,188,1)",
              data: tabConsultation
            },
			
			{
			 label: "Ordonnances",
              fillColor: "rgba(210, 214, 222, 1)",
              strokeColor: "rgba(210, 214, 222, 1)",
              pointColor: "rgba(210, 214, 222, 1)",
              pointStrokeColor: "#c1c7d1",
              pointHighlightFill: "#fff",
              pointHighlightStroke: "rgba(220,220,220,1)",
              data: tabOrdonnance
            },
            {
              label: "",
              fillColor: "rgba(255,165,0,0.9)",
              strokeColor: "rgba(255,165,0,0.8)",
              pointColor: "#3b8bba",
              pointStrokeColor: "rgba(255,165,0,1)",
              pointHighlightFill: "#fff",
              pointHighlightStroke: "rgba(255,165,0,1)",
              data: tabExamen
            }
          ]
        };
       
        

        var barChartCanvas = $("#barChart-"+$( '#selectAnnee' ).val()).get(0).getContext("2d");
		console.log(barChartCanvas);
		
		barChart = new Chart(barChartCanvas);
	
        var barChartData = areaChartData;
        barChartData.datasets[1].fillColor = "#00a65a";
        barChartData.datasets[1].strokeColor = "#00a65a";
        barChartData.datasets[1].pointColor = "#00a65a";
		
        var barChartOptions = {
          //Boolean - Whether the scale should start at zero, or an order of magnitude down from the lowest value
          scaleBeginAtZero: true,
          //Boolean - Whether grid lines are shown across the chart
          scaleShowGridLines: true,
          //String - Colour of the grid lines
          scaleGridLineColor: "rgba(0,0,0,.05)",
          //Number - Width of the grid lines
          scaleGridLineWidth: 1,
          //Boolean - Whether to show horizontal lines (except X axis)
          scaleShowHorizontalLines: true,
          //Boolean - Whether to show vertical lines (except Y axis)
          scaleShowVerticalLines: true,
          //Boolean - If there is a stroke on each bar
          barShowStroke: true,
          //Number - Pixel width of the bar stroke
          barStrokeWidth: 2,
          //Number - Spacing between each of the X value sets
          barValueSpacing: 5,
          //Number - Spacing between data sets within X values
          barDatasetSpacing: 1,
          //String - A legend template
          legendTemplate: "<ul class=\"<%=name.toLowerCase()%>-legend\"><% for (var i=0; i<datasets.length; i++){%><li><span style=\"background-color:<%=datasets[i].fillColor%>\"></span><%if(datasets[i].label){%><%=datasets[i].label%><%}%></li><%}%></ul>",
          //Boolean - whether to make the chart responsive
          responsive: true,
          maintainAspectRatio: true
        };

        barChartOptions.datasetFill = false;
        barChart.Bar(barChartData, barChartOptions);
		 
		
		
      });
								
								///
								
								
								
									
								});
							});
						};
						
						
	

tutorielRun();

	
     
			
		</script>
		
		
    </body>
</html>