<?php
	
	use Zend\Session\Container;
	
	$sessionUtilisateur = new Container('utilisateur');
	$sessionAppli = new Container('appli');
	
	$nomCompletEmploye = $sessionUtilisateur->offsetGet("nom")." ".$sessionUtilisateur->offsetGet("prenom");
	
	function construireSousMenu($unMenu, $phpRender)
	{
		$varRetour = "";
		
		$nbreSousMenus = 0;
		if(isset($unMenu['sousMenus']) && is_array($unMenu['sousMenus']))
			$nbreSousMenus = count($unMenu['sousMenus']);
		
		$classMenu = "";
		$iconeMenu = "";
		if($nbreSousMenus > 0)
		{
			$classMenu = "treeview";
			$iconeMenu = '  <i class="fa fa-angle-left pull-right"></i>';
		}
		
		$classActive = "";
		if(substr_count(str_replace("/public", "/", $_SERVER['REQUEST_URI']), str_replace("/public", "/", $unMenu['url'])) > 0)
			$classMenu .= ' active';
		
		
		if($unMenu['classImage'] && $unMenu['classImage'] != "")
			$classImage = $unMenu['classImage'];
		else
			$classImage = "fa fa-circle-o";
		
		
		$varRetour .= '<li class="'.$classMenu.'">';
		
		$varRetour .= '<a href="'.$phpRender->basePath($unMenu['url']).'">
						 <i class="'.$classImage.'"></i> <span>'.$unMenu['nom'].'</span>'.$iconeMenu.'
					   </a>';
		
		if($nbreSousMenus > 0)
		{
			$varRetour .= '<ul class="treeview-menu">';
			
			$tabSousMenu = $unMenu['sousMenus'];
			
			foreach ($tabSousMenu as $unSousMenu)
			{
				$varRetour .= construireSousMenu($unSousMenu, $phpRender);
			}
			
			$varRetour .= '</ul>';
		}
		
		$varRetour .= '</li>';
		
		return $varRetour;
	}
	
?>

<!-- sidebar: style can be found in sidebar.less -->
<section class="sidebar">
  <!-- Sidebar user panel -->
  <div class="user-panel">
	<div class="pull-left image">
	  <img src="<?= $this->basePath('AdminLTE-2.2.1/dist/img/user2-160x160.png')?>" class="img-circle" alt="User Image">
	</div>
	<div class="pull-left info">
	  <p><?= $nomCompletEmploye; ?></p>
	  <a href="#"><i class="fa fa-circle text-success"></i> <?= $this->translate("En ligne", "application"); ?></a>
	</div>
  </div>
  <!-- sidebar menu: : style can be found in sidebar.less -->
  <ul class="sidebar-menu">
	
	
	<?php
		foreach ($this->tabMenu as $unMenu)
		{
			echo construireSousMenu($unMenu, $this);
		}
	?>
	
  </ul>
</section>
<!-- /.sidebar -->