<?php if(is_array($this->buttonOptions)) : ?>
	
	<?php if(isset($this->buttonOptions['btn_ajouter']) && isset($this->buttonOptions['btn_ajouter']['url'])) : ?>
		<div class="pull-right">
			<?php 
			
			if(substr($this->buttonOptions['btn_ajouter']['url'], 0, 1) == "#")
				$href = $this->buttonOptions['btn_ajouter']['url'];
			else
				$href = $this->basePath($this->buttonOptions['btn_ajouter']['url']);
			?>
			
			<a class="btn btn-default" href="<?= $href; ?>" id="btnAjoutApp">
				<i class="fa fa-plus"></i> <?= $this->translate("Ajouter", "application"); ?>
			</a>
		</div>
	<?php endif; ?>
	
	<?php if(isset($this->buttonOptions['btn_activer']) && $this->buttonOptions['btn_activer'] == true) : ?>
		<div class="pull-right">
			<a class="btn btn-default" id="activer_commun">
				<i class="fa fa-check-square-o"></i> <?= $this->translate("Activer", "application"); ?>
            </a>
        </div>
	<?php endif; ?>
	
	<?php if(isset($this->buttonOptions['btn_desactiver']) && $this->buttonOptions['btn_desactiver'] == true) : ?>
		<div class="pull-right">
			<a class="btn btn-default" id="desactiver_commun">
				<i class="fa fa-close"></i> <?= $this->translate("Desactiver", "application"); ?>
			</a>
		</div>
	<?php endif; ?>
	
	<?php if(isset($this->buttonOptions['btn_supprimer']) && $this->buttonOptions['btn_supprimer'] == true) : ?>
		<div class="pull-right">
			<a class="btn btn-default" id="supprimer_commun">
				<i class="fa fa-trash-o"></i> <?= $this->translate("Supprimer", "application"); ?>
			</a>
		</div>
	<?php endif; ?>
	
	
	<?php if(isset($this->buttonOptions['btn_imprimer']) && isset($this->buttonOptions['btn_imprimer']['url'])) : ?>
		<div class="pull-right">
			<?php 
			
			if(substr($this->buttonOptions['btn_imprimer']['url'], 0, 1) == "#")
				$href = $this->buttonOptions['btn_imprimer']['url'];
			else
				$href = $this->basePath($this->buttonOptions['btn_imprimer']['url']);
			?>
			
			<a class="btn btn-default" href="" id="btnImprimerApp" data-toggle="modal" data-target="#ctneurMdleImprimer" urlAction="<?= $href; ?>">
				<i class="fa fa-print"></i> <?= $this->translate("Exporter", "application"); ?>
			</a>
		</div>
		
		
		
		<div class="modal fade" id="ctneurMdleImprimer" role="dialog">
			<div class="modal-dialog">
				<!-- Modal content-->
			    <div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
						<h4 class="modal-title" id="titleConnexionModale"><?= $this->translate("Choix format de l'export", "application"); ?></h4>
					</div>
					<div class="modal-body" id="divBodyFormAjaxImprimer">
						<form action="" id="formAjaxImprimer" method="post">
							<button type="button" class="btn btn-primary" id="imprimerPdfBtn" name="imprimerPdfBtn" typeImpression="pdf"><?= $this->translate("PDF", "application"); ?></button>
							<button type="button" class="btn btn-primary" id="imprimerCsvBtn" name="imprimerCsvBtn" typeImpression="csv"><?= $this->translate("EXCEL", "application"); ?></button>
						</form>
					</div>
				</div><!-- /.modal-content -->
		    </div>
		</div>
		
		
		
	<?php endif; ?>
	
<?php endif; ?>