<?= $this->doctype(); ?>

<?php
	use Zend\Session\Container;
	
	$sessionInternaute = new Container('internaute');
	$sessionAgence = new Container('agence');
	
	$appliConfig =  new \Application\Core\AppliConfig();
	
	$idInternauteHere = $sessionInternaute->offsetGet("id");
	
	if(isset($this->titleHautPage) && !empty($this->titleHautPage))
		$titlePage = $this->titleHautPage;
	else
		$titlePage = $this->nomPage;
?>

<html lang="<?= $sessionInternaute->offsetGet("code_iso_langue"); ?>" class="">
    <head>
    	<script src="https://apis.google.com/js/platform.js" async defer></script>
		<meta name="google-signin-client_id" content="490762090175-5e17eni67sl3l5dgor9g10v0atr04rc4.apps.googleusercontent.com">
		
    	
    	<!-- Basic -->
		<meta http-equiv='Content-Type' content='text/html; charset=utf-8' />
		<meta http-equiv='X-UA-Compatible' content='IE=Edge,chrome=1' />

		<title><?= $titlePage." - ".$this->translate($appliConfig->get("nom_appli"), "application"); ?></title>	

		<?php if(isset($this->metaMotClePage) && !empty($this->metaMotClePage)) : ?>
			<meta name="keywords" content="<?= $this->metaMotClePage; ?>" />
		<?php endif ; ?>
		
		<?php if(isset($this->metaDescriptionPage) && !empty($this->metaDescriptionPage)) : ?>
			<meta name="description" content="<?= $this->metaDescriptionPage; ?>" />
		<?php endif ; ?>
		
		<meta name="author" content="<?= $appliConfig->get("nom_appli"); ?>" />

		<!-- Favicon -->
		<link rel="shortcut icon" href="<?= $this->basePath("img/favicon.ico"); ?>" type="image/x-icon" />
		<link rel="apple-touch-icon" href="<?= $this->basePath("img/apple-touch-icon.png"); ?>" />

		<!-- Mobile Metas -->
		<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">

		<!-- Web Fonts  -->
		<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800%7CShadows+Into+Light" rel="stylesheet" type="text/css" />
		
		<!-- Sticky Modal -->
		<link rel="stylesheet" href="<?= $this->basePath("modal-css3-powered-popups/css/slickModal.min.css"); ?>" media="screen" />
		<link rel="stylesheet" href="<?= $this->basePath("Hover-master/css/hover-min.css"); ?>" media="screen" />

		<!-- Vendor CSS -->
		<link rel="stylesheet" href="<?= $this->basePath("vendor/bootstrap/css/bootstrap.min.css"); ?>" />
		<link rel="stylesheet" href="<?= $this->basePath("css/bootstrap-social.css"); ?>" />
		
		<link rel="stylesheet" href="<?= $this->basePath("js/jqueryui/development-bundle/themes/base/jquery.ui.all.css"); ?>" />
		<link rel="stylesheet" href="<?= $this->basePath("AdminLTE-2.2.1/plugins/ionicons.min.css"); ?>" />
		<link rel="stylesheet" href="<?= $this->basePath("AdminLTE-2.2.1/plugins/select2/select2.min.css"); ?>" />
		<link rel="stylesheet" href="<?= $this->basePath("AdminLTE-2.2.1/plugins/iCheck/all.css"); ?>" />
		<link rel="stylesheet" href="<?= $this->basePath("AdminLTE-2.2.1/plugins/datatables/dataTables.bootstrap.css"); ?>" />
		
		
		
		
		
		<link rel="stylesheet" href="<?= $this->basePath("vendor/font-awesome/css/font-awesome.min.css"); ?>" />
		<link rel="stylesheet" href="<?= $this->basePath("vendor/owl.carousel/assets/owl.carousel.min.css"); ?>" />
		<link rel="stylesheet" href="<?= $this->basePath("vendor/owl.carousel/assets/owl.theme.default.min.css"); ?>" />

		<!-- Theme CSS -->
		<link rel="stylesheet" href="<?= $this->basePath("css/theme.css"); ?>" />
		<link rel="stylesheet" href="<?= $this->basePath("css/theme-elements.css"); ?>" />
		<link rel="stylesheet" href="<?= $this->basePath("css/theme-blog.css"); ?>" />

		<!-- Skin CSS -->
		<link rel="stylesheet" href="<?= $this->basePath("css/skins/default.css"); ?>" />		

		<!-- Theme Custom CSS -->
		<link rel="stylesheet" href="<?= $this->basePath("css/custom.blue.css"); ?>" />
		
		<link rel="stylesheet" href="<?= $this->basePath("vendor/intl-tel-input/build/css/intlTelInput.css"); ?>" />
		
		<link rel="stylesheet" href="<?= $this->basePath("vendor/animate.css/3.4.0/animate.min.css"); ?>" />
		
		<link rel="stylesheet" href="<?= $this->basePath("js/jquery-confirm-master-v3-0-1/css/jquery-confirm.css"); ?>" />
		
		<link rel="stylesheet" href="<?= $this->basePath("js/spinner-on-div/spinnerQueue.css"); ?>" />
		
		<link rel="stylesheet" href="<?= $this->basePath("css/custom.css"); ?>" />
		<link rel="stylesheet" href="<?= $this->basePath("css/style.css"); ?>" />
		
		<?php if($appliConfig->get("mode_demo") == "0") : ?>
			<link rel="stylesheet" href="<?= $this->basePath("css/production.css"); ?>" />
		<?php endif; ?>
		
		<link rel="stylesheet" href="<?= $this->basePath("css/langage/".$sessionInternaute->offsetGet("code_langue").".css"); ?>" />
		
		
		<?= $this->headScript()
        	->prependFile($this->basePath().'/js/script.js')
        	->prependFile($this->basePath().'/js/custumPagination.js', 'text/javascript')
        	->prependFile($this->basePath().'/js/language/common_lang_'.$sessionInternaute->offsetGet("code_langue").'.js')
        	
        	->prependFile($this->basePath().'/js/spinner-on-div/spinnerQueue.js', 'text/javascript')
        	
        	->prependFile($this->basePath().'/vendor/intl-tel-input/build/js/intlTelInput.min.js', 'text/javascript')
        	
        	->prependFile($this->basePath().'/js/jquery.maskedinput.js', 'text/javascript')
        	 
        	// FormValidation
        	->prependFile($this->basePath().'/js/formValidation/js/bootstrap.min.js', 'text/javascript')
        	->prependFile($this->basePath().'/js/formValidation/js/formValidation.min.js', 'text/javascript')
        	
        	->prependFile($this->basePath().'/js/jquery-confirm-master-v3-0-1/js/jquery-confirm.js')
        	
        	->prependFile($this->basePath().'/js/jquery.jqprint-0.3.js', 'text/javascript')
        	->prependFile($this->basePath().'/AdminLTE-2.2.1/plugins/input-mask/jquery.inputmask.numeric.extensions.js', 'text/javascript')
        	->prependFile($this->basePath().'/AdminLTE-2.2.1/plugins/input-mask/jquery.inputmask.extensions.js', 'text/javascript')
        	->prependFile($this->basePath().'/AdminLTE-2.2.1/plugins/input-mask/jquery.inputmask.js', 'text/javascript')
        	->prependFile($this->basePath().'/js/jquery.alerts.js')
        	->prependFile($this->basePath('AdminLTE-2.2.1/plugins/select2/select2.full.min.js'))
        	->prependFile($this->basePath('AdminLTE-2.2.1/plugins/iCheck/icheck.min.js'))
        	
        	// Vendor
        	->prependFile($this->basePath().'/vendor/owl.carousel/owl.carousel.min.js')
            ->prependFile($this->basePath().'/vendor/common/common.min.js')
            ->prependFile($this->basePath().'/vendor/bootstrap/js/bootstrap.min.js')
            ->prependFile($this->basePath().'/vendor/jquery-cookie/jquery-cookie.min.js')
            
            
            ->prependFile($this->basePath().'/js/jqueryui/development-bundle/ui/minified/jquery.ui.datepicker.min.js', 'text/javascript')
            ->prependFile($this->basePath().'/js/jqueryui/development-bundle/ui/minified/jquery.ui.widget.min.js', 'text/javascript')
            ->prependFile($this->basePath().'/js/jqueryui/development-bundle/ui/minified/jquery.ui.core.min.js', 'text/javascript')
            
            ->prependFile($this->basePath().'/modal-css3-powered-popups/js/slickModal.min.js', 'text/javascript')
            
            ->prependFile($this->basePath().'/vendor/jquery/jquery.min.js')
            ->prependFile($this->basePath().'/vendor/modernizr/modernizr.min.js')
        ; ?>
	</head>
	
    <body data-spy="scroll" data-target="#sidebar">
		
		<div class="loading-overlay">
			<div class="loader"></div>
		</div>

		<div class="body">
			<header id="header" class="header-narrow" data-plugin-options='{"stickyEnabled": true, "stickyEnableOnBoxed": true, "stickyEnableOnMobile": false, "stickyStartAt": 47, "stickySetTop": "-47px", "stickyChangeLogo": false}'>
				<?= $this->header; ?>
			</header>

			<div role="main" class="main">

				<section class="page-header">
					<div class="container">
						<!--  
							<div class="row">
								<div class="col-md-12">
									<?php // echo $this->contenuNavigation; ?>
								</div>
							</div>
						-->
						<div class="row">
							<div class="col-md-12">
								<h1><?= $this->nomPage; ?></h1>
							</div>
						</div>
					</div>
				</section>

				<div class="container contenuPage" id="contenuPage">

					<div class="row">
						<div class="col-md-12">
							
							<?php if(isset($this->codeHtmlBefore)) : ?>
								<?= $this->codeHtmlBefore; ?>
							<?php endif ; ?>
							
							
							<?php if (isset($this->actionsList) && !empty($this->actionsList)) : ?>
								<div class="box-header" id="cteneurActionList">
									<?= $this->actionsList; ?>
									<div class="clearBoth"></div>
								</div>
							<?php endif ; ?>
							
							
							<?php if (isset($this->filtre)  && !empty($this->filtre)) : ?>
								<!-- general form elements -->
								<div class="box box-primary box-primary-adminlte">
									<form role="form" id="formFiltreListeElt">
										<div class="box-body">
							                <?= $this->filtre; ?>  
										</div><!-- /.box-body -->
									</form>
									<div class="clearBoth"></div>
								</div><!-- /.box -->
							<?php endif ; ?>
							
							<?php if(isset($this->optionsOnglets) && is_array($this->optionsOnglets) && count($this->optionsOnglets) > 0) : ?>

								<div class="box box-primary">
									<?= $this->onglet; ?>
								</div><!-- /.box -->
								
							<?php endif ; ?>
							
							
							<div id="ctneurLiteEltsTab" class="blog-posts ctneurLiteEltsTab"></div>
							<?= $this->content; ?>
						</div>
						
					</div>

				</div>

			</div>

			<footer id="footer">
				<?= $this->footer; ?>
			</footer>
		</div>
		
		
		<!-- Theme Base, Components and Settings -->
		<script src="<?= $this->basePath("js/theme.js"); ?>"></script>
		
		<script src="<?= $this->basePath("js/theme.init.js"); ?>"></script>
		
		
		<!-- Theme Custom -->
		<script src="<?= $this->basePath("js/custom.js"); ?>"></script>
		
		<!-- Theme Initialization Files -->
		<script src="<?= $this->basePath("js/theme.customMsbt.init.js"); ?>"></script>
		
		
        <?= $this->inlineScript(); ?>
        
        
        <?php 
			include_once __DIR__.'/common.phtml';
        	// include_once __DIR__.'/common/pop-up-annonce.phtml';
		?>
        
        
        <script type="text/javascript">		         
			$(document).ready(function() {

				basePathLangue = "<?= $this->basePath()."/".$sessionInternaute->offsetGet("code_iso_langue"); ?>";

				
		        $("#formFiltreListeElt select").select2();
		        $("#formFiltreListeElt input.number").inputmask('decimal',
		        	{ 
			        	'alias': 'numeric',
			            'groupSeparator': '  ',
			            'autoGroup': true,
			            'digits': 2,
			            'radixPoint': ",",
			            'digitsOptional': false,
			            'allowMinus': false,
			            'rightAlign': false
		          }
		        );
		
		        $( "input[type='text'].date" ).datepicker({
		            changeYear: true,
		            changeMonth: true,
		            numberOfMonths: 1,
		            dateFormat: "yy-mm-dd"
		        });

		        $('form .form-group label[class="msbt-tooltip"]').tooltip({"html" : true, "placement": "right", "trigger": "hover"});
		
		        $("#formFiltreListeElt").on("change", "select, input[type='text'], input[type='number']", function() {
					choisirPage(1);
		        });
		
		        $("body").on("click", "table.tableSortinMsbt tr th.isOrdered", function() {
		
					$this = $(this);
		
					nomColoneTriPagination = $this.attr("nomColone");
					
					if($this.hasClass("sorting_asc")) 
					{
						typeTriColonePagination = "DESC";
						otherElementsToPost = "&nomColoneTriPagination="+nomColoneTriPagination+"&typeTriColonePagination="+typeTriColonePagination+"&nbreMaxLigneTableau="+nbreMaxLigneTableau;
					}
					else
					{
						typeTriColonePagination = "ASC";
						otherElementsToPost = "&nomColoneTriPagination="+nomColoneTriPagination+"&typeTriColonePagination="+typeTriColonePagination+"&nbreMaxLigneTableau="+nbreMaxLigneTableau;
					}
					
		        	choisirPage(1);
		        });
		
		        $("body").on("change", "#selectNbreLignePagin", function() {
		
					$this = $(this);
					nbreMaxLigneTableau = $this.val();
					otherElementsToPost = "&nomColoneTriPagination="+nomColoneTriPagination+"&typeTriColonePagination="+typeTriColonePagination+"&nbreMaxLigneTableau="+nbreMaxLigneTableau;
					
		        	choisirPage(1);
		        });
		
		        $("body").on("click", ".btn-modifier-heres", function() {
					$this = $(this);
					window.location = $this.attr("href");
		        });
		
		        cheminControlleurPaginHere = '<?= $this->cheminPagination; ?>';
		        idDivConteneurPaginHere = 'ctneurLiteEltsTab';
		        idFormPaginHere = "formFiltreListeElt";        
		        
		        choisirPage(1);
			});
		</script>
		
		<?php 
			include_once __DIR__.'/common/liveChat.phtml';
		?>
		
		<?php 
			if(empty($idInternauteHere))
			{
				include_once __DIR__.'/../../../FrontAuth/view/front-auth/index/ajaxConnexion.phtml';
			}
		?>
		
    </body>
</html>