<?php 

use Zend\Session\Container;
$sessionAgence = new Container('agence');
$sessionEmploye = new Container('employe');

$appliConfig =  new \Application\Core\AppliConfig();

$typeProfil = $sessionEmploye->offsetGet("type_profil");
$typeSousProfil = $sessionEmploye->offsetGet("type_sous_profil");


$varRetour .= '<form class="form-horizontal fv-form fv-form-bootstrap" id="form_details_prestation">';
$varRetour .= '<table class="table dataTable table-hover table-bordered table-striped tableSortinMsbt" id="liteEltsTab">';
$varRetour .= '  <thead>';
$varRetour .= '    <tr>';
// $varRetour .= '        <th class="rsv-table-title-checkbox"><input type="checkbox" name="check_all_list" id="check_all_list" /></th>';


if($typeProfil == "admin" || $typeSousProfil == "centre_hospitalier")
{
    $varRetour .= '        <th>'.$this->getTranslator("Prestataire").'</th>';
}




    $varRetour .= '        <th>'.$this->getTranslator("Type prestation").'</th>';


    
    $varRetour .= '        <th>'.$this->getTranslator("Valeur").'</th>';

$varRetour .= '        <th>'.$this->getTranslator("Observations").'</th>';
$varRetour .= '        <th style="width: 140px;">'.$this->getTranslator("Etat").'</th>';

$varRetour .= '        <th class="rsv-table-title-action">'.$this->getTranslator("Actions").'</th>';


$varRetour .= '    </tr>';
$varRetour .= '  </thead>';
$varRetour .= '  <tbody>';


//
$tabLignePrestation = array();

$idPrestataireMettrePrix = null;

foreach($tab as $element)
{
    $prestation = $element->getPrestation();
    $visite = $prestation->getVisite();
    $prestataire = $visite->getPrestataire();
    $prestataireMettrePrix = $element->getPrestataire();
    $adherent = $visite->getCodeAdherent();
    $ayantDroit = $visite->getCodeAyantDroit();
    
    $prestation->afficheChaine();
    $element->afficheChaine();
    $prestataire->afficheChaine();
    $adherent->afficheChaine();
    
    $nomAyantDroit = "";
    if($ayantDroit)
    {
        $ayantDroit->afficheChaine();
        $nomAyantDroit = $ayantDroit->getNom();
    }
    
    // Verivier si la ligne doit etre affichee
    if($typeProfil != "admin")
    {
        if($prestataire->getId() != $sessionEmploye->offsetGet("id_prestataire"))
        {
            if($prestataireMettrePrix && ($prestataireMettrePrix->getId() != $sessionEmploye->offsetGet("id_prestataire")))
            {
                continue;
            }
        }
    }
    
    
    
    $typePrestation = "";
    
        if($element->getTypeExamen())
        {
            $typePrestation = $element->getTypeExamen()->getId();
        }
    
    
    
    $afficherValiderLignePrestationButton = $this->lignePrestationManager->vefifierSiLignePrestationValidable($element) && $peuxValiderLignePrestation;
    $afficherRejeterLignePrestationButton = $this->lignePrestationManager->vefifierSiLignePrestationRejetable($element) && $peuxRejeterLignePrestation;
    $afficherEncaisserLignePrestationButton = $this->lignePrestationManager->vefifierSiLignePrestationEncaissable($element, $sessionEmploye->offsetGet("id_prestataire")) && $peuxEncaisserLignePrestation;
    $afficherMettrePrixLignePrestationButton = $this->lignePrestationManager->vefifierSiLignePrestationMettrePrix($element) && $peuxMettrePrixLignePrestation;
    
    
    
    //$afficherDevaliderLignePrestationButton = $this->lignePrestationManager->vefifierSiLignePrestationDevalidable($element) && $peuxDevaliderLignePrestation;
    $afficherDerejeterLignePrestationButton = $this->lignePrestationManager->vefifierSiLignePrestationDerejetable($element) && $peuxDerejeterLignePrestation;
    
    
    $afficherSupprimerLignePrestationButton = $this->lignePrestationManager->vefifierSiLignePrestationSupprimable($element);
   


    if($element->getEtat() == "valide")
    {
        $montantPropose = $element->getValeurModif();
    }

    
    
    $tabLignePrestation[] = array("id" => $element->getId(),
        "nom" => $element->getNom(),
        "prestation" => $element->getPrestation()->getId(),
        "valeur" => $element->getValeur(),
        "nbre" => $element->getNbre(),
        "afficherValiderLignePrestationButton" => $afficherValiderLignePrestationButton,
        "afficherRejeterLignePrestationButton" => $afficherRejeterLignePrestationButton,
        "afficherEncaisserLignePrestationButton" => $afficherEncaisserLignePrestationButton,
        "afficherMettrePrixLignePrestationButton" => $afficherMettrePrixLignePrestationButton,
        
        
        //"afficherDevaliderLignePrestationButton" => $afficherDevaliderLignePrestationButton,
        "afficherDerejeterLignePrestationButton" => $afficherDerejeterLignePrestationButton,
    );
    
    
    $classLigne = $element->getEtat();
    
    switch ($element->getEtat()) {
        case "enregistre":
            $clasCssImgEtat = "fa-save";
            $titleImgEtat = $this->getTranslator("Enregistre");
            $classCouleur = "text-aqua";
            ;
            break;
        
        case "attente_validation":
            $clasCssImgEtat = "fa-hourglass-start";
            $titleImgEtat = $this->getTranslator("Attente de validation");
            $classCouleur = "text-orange";
            ;
            break;
            
        case "rejete":
            $clasCssImgEtat = "fa-close";
            $titleImgEtat = $this->getTranslator("Rejete");
            $classCouleur = "text-red";
            ;
            break;
            
        case "valide":
            $clasCssImgEtat = "fa-check";
            $titleImgEtat = $this->getTranslator("Valide");
            $classCouleur = "text-green";
            ;
            break;
            
        case "encaisse":
            $clasCssImgEtat = "fa-dollar";
            $titleImgEtat = $this->getTranslator("Encaisse");
            $classCouleur = "text-navy";
            ;
            break;
            
        default:
            $clasCssImgEtat = "";
            $titleImgEtat = "";
            break;
    }
    
    
    
    
   
    
    $valeurModif = $element->getPosologie();
    if(empty($valeurModif))
    {
        $valeurModif = $element->getValeur();
    }
    
    
    $contenuMontantModif = $valeurModif;
    $contenuObservations = $element->getObservations();
    
   
    
    $colonneEtatLignePrestation = '<div class="'.$classCouleur.'"><i class="fa '.$clasCssImgEtat.'"></i>  '.$titleImgEtat.'</div>';
    
    if($element->getEtat()=="valide")
	{
    $varRetour .= '    <tr id="lignePretation_'.$element->getId().'" class="'.$classLigne.'" rel="'.$element->getId().'">';
	// $varRetour .= '        <td class="rsv-table-elt-btn"><input type="checkbox" name="elt_check_tableau" class="elt_check_tableau" rel="'.$element->getId().'" /></td>';
	
	if($typeProfil == "admin" || $typeSousProfil == "centre_hospitalier")
	{
	    $nomPrestataire = "";
	    if($prestataireMettrePrix)
	    {
	        $prestataire->afficheChaine();
	        $nomPrestataire = $prestataireMettrePrix->getNom();
	    }
	    
	    $varRetour .= '        <td class="prestataire_detailsPrestation" id="prestataire_detailsPrestation_'.$element->getId().'">'.$nomPrestataire.'</td>';
	}
	
	
	
	
	
		$nomTypeExamen = "";
		if($element->getTypeExamen())
		{
			$nomTypeExamen = $element->getTypeExamen()->getNom();
		}
		
	    $varRetour .= '        <td class="typeExamen_detailsPrestation" id="typeExamen_detailsPrestation_'.$element->getId().'">'.$nomTypeExamen.'</td>';
	    
	    $varRetour .= '        <td class="valeurModif_detailsPrestation" id="valeurModif_detailsPrestation_'.$element->getId().'">'.$contenuMontantModif.'</td>';
	
	
	
	$varRetour .= '        <td class="observations_detailsPrestation" id="observations_detailsPrestation_'.$element->getId().'">'.$contenuObservations.'</td>';
	
	$varRetour .= '        <td class="etat_detailsPrestation" id="etat_detailsPrestation_'.$element->getId().'">'.$colonneEtatLignePrestation.'</td>';	
	
	$varRetour .= '        <td class="rsv-table-elt-btn action_detailsPrestation" id="action_detailsPrestation_'.$element->getId().'">';
	$varRetour .= '             <select name="actionLignePretation_'.$element->getId().'" id="actionLignePretation_'.$element->getId().'" rel="'.$element->getId().'" class="form-control actionLignePretation" style="display: inline-block; width: 130px;">
							       <option value="">'.$this->getTranslator("Selectionnez").'</option>';
    
	
	if($afficherValiderLignePrestationButton)
	{
	    $varRetour .= '<option value="valide" name="actionLignePretation_'.$element->getId().'" id="actionLignePretation_'.$element->getId().'">'.$this->getTranslator("Valider").'</option>';
	}
	
	if($afficherRejeterLignePrestationButton)
	{
	    $varRetour .= '<option value="rejete" name="actionLignePretation_'.$element->getId().'" id="actionLignePretation_'.$element->getId().'">'.$this->getTranslator("Rejeter").'</option>';
	}
	
	
	
	
	
	
	//if($afficherDevaliderLignePrestationButton)
	//{
	 //   $varRetour .= '<option value="devalide" name="actionLignePretation_'.$element->getId().'" id="actionLignePretation_'.$element->getId().'">'.$this->getTranslator("Devalider").'</option>';
	//}
	
	if($afficherDerejeterLignePrestationButton)
	{
	    $varRetour .= '<option value="derejete" name="actionLignePretation_'.$element->getId().'" id="actionLignePretation_'.$element->getId().'">'.$this->getTranslator("Derejeter").'</option>';
	}
	                                           
    
	$varRetour .= '             </select>';
	
                                               

	$varRetour .= '        </td>';
	
	
	
	$varRetour .= '    </tr>';
		
	}
	
	if($prestataireMettrePrix)
	{
	    $prestataireMettrePrix->afficheChaine();
	    
	    $nomPrestataireMettrePrix = $prestataireMettrePrix->getNom();
	    $idPrestataireMettrePrix = $prestataireMettrePrix->getId();
	}
	else
	{
	    $nomPrestataireMettrePrix = "";
	    $idPrestataireMettrePrix = null;
	}
	
}


$varRetour .= '  </tbody>';
$varRetour .= '</table>';



$jsonTabLignePrestation = json_encode($tabLignePrestation);


$varRetour .= '<div class="box-footer">';
$varRetour .= ' <input name="submit" type="submit" id="soumettre" class="btn btn-primary form-control pull-right" style="" value="'.$this->getTranslator("Soumettre").'" />';
$varRetour .= ' <a href="'.$basePath.'/'.$appliConfig->get('lienBackoffice').'/'.$this->naturePrestation.'"><input name="cancel" type="button" id="cancel" class="btn btn-default form-control pull-right" value="Retour"></a>';
$varRetour .= '</div>';

$varRetour .= '</form>


<style type="text/css">

    .ctneurTotaux {
        text-align: right;
        margin-bottom: 50px;
        font-size: 18px;
    }

    .titreTotal, .valeurTotal {
        display: inline-block;
    }

    .valeurTotal {
        font-weight: bold;
    }

    tr.enregistre {
        background: #f5e0cf !important;
    }
</style>


<script type="text/javascript">';

$varRetour .= "   tabLignePrestation = jQuery.parseJSON('".addslashes($jsonTabLignePrestation)."');";
// $varRetour .= "   listeLignePrestationSent = ".$jsonTabLignePrestation.";";
    
$varRetour .= '	initialiserJsLignePrestation();

</script>

';

?>